### ISSUE TITLE
ValueError: 'accuracy' is not in list

### ISSUE THREAD

**Issue by leige666nb** [Deci-AI/super-gradients#1026]
###ERRORS

#Errors thrown by custom datasets

[2023-05-17 13:37:27] ERROR - sg_trainer_utils.py - Uncaught exception
Traceback (most recent call last):
  File "D:\project(yolo)\Yolo_nas_costom_datasets\yolo_nas.py", line 140, in <module>
    main()
  File "D:\project(yolo)\Yolo_nas_costom_datasets\yolo_nas.py", line 117, in main
    trainer.train(model=model,training_params=train_params,
  File "D:\anaconda\envs\yolo\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 1240, in train
    train_metrics_tuple = self._train_epoch(epoch=epoch, silent_mode=silent_mode)
  File "D:\anaconda\envs\yolo\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 441, in _train_epoch
    loss, loss_log_items = self._get_losses(outputs, targets)
  File "D:\anaconda\envs\yolo\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 485, in _get_losses
    self._init_monitored_items()
  File "D:\anaconda\envs\yolo\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 499, in _init_monitored_items
    self.metric_idx_in_results_tuple = fuzzy_idx_in_list(self.metric_to_watch, self.loss_logging_items_names + get_metrics_titles(self.valid_metrics))
  File "D:\anaconda\envs\yolo\lib\site-packages\super_gradients\training\utils\utils.py", line 226, in fuzzy_idx_in_list
    return [fuzzy_str(x) for x in lst].index(fuzzy_str(name))
ValueError: 'accuracy' is not in list

why?

###The following are the defined parameters for training
train_params = {
        "silent_mode": True,  # Silents the Print outs
        "average_best_models": True,
        "warmup_mode": "linear_epoch_step",
        "warmup_initial_lr": 1e-6,
        "lr_warmup_epochs": 5,
        "initial_lr": 5e-4,
        "lr_mode": "cosine",
        "cosine_final_lr_ratio": 0.1,
        "optimizer": "Adam",
        "optimizer_params": {"weight_decay": 0.0001},
        "zero_weight_decay_on_bias_and_bn": True,
        "ema": True,
        "ema_params": {"decay": 0.9,"decay_type": "threshold"},
        "max_epochs": 100,
        "mixed_precision": True,
        "loss": PPYoloELoss(
                 use_static_assigner=False,
                 num_classes=len(dataset_params['classes']),
                 reg_max=16,
        ),
        "valid_metrics_list": [
            DetectionMetrics_050(
                num_cls=len(dataset_params['classes']),
                normalize_targets=True,
                score_thres=0.1,
                top_k_predictions=100,
                post_prediction_callback=PPYoloEPostPredictionCallback(
                    score_threshold=0.1,
                    nms_top_k=1000,
                    max_predictions=300,
                    nms_threshold=0.7,
                )
            )
        ],
        "metic_to_watch": "mAP@0.50"
    }

**Comment by shaydeci** [comment]
Thanks @leige666nb ,seems like you have a typo in "metic_to_watch", thats why you are taking a default metric_to_watch but without the default metrics (accuracy is a default).
Change to "metric_to_watch" and it should work.
