### ISSUE TITLE
Output Weights & Biases log in Windows

### ISSUE THREAD

**Issue by momonoki3nenn** [Deci-AI/super-gradients#1028]
Add parameters with reference to [site](https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/experiment_monitoring.md).
However, 'api_server' A did not add.

Error when outputting Weights & Biases log.

・Error
`File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 1616, in _initialize_sg_logger_objects
    self.sg_logger = sg_logger_cls(**sg_logger_params)
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\super_gradients\common\sg_loggers\wandb_sg_logger.py", line 104, in __init__
    self._set_wandb_id(run.id)
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\super_gradients\common\sg_loggers\wandb_sg_logger.py", line 265, in _set_wandb_id        
    os.mknod(os.path.join(self._local_dir, f"{WANDB_ID_PREFIX}{id}"))      
AttributeError: module 'os' has no attribute 'mknod'`

'mknod' is not available in WIndows

Corrected `os.mknod(os.path.join(self._local_dir, f"{WANDB_ID_PREFIX}{id}"))` to `wandb_id=Path(self._local_dir).joinpath(f'{WANDB_ID_PREFIX}{id}')　wandb_id.touch()`.

Error occurred after correction(Partial correction)
`
wandb: Currently logged in as: ******. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.2
wandb: Run data is saved locally in C:\projects\evaluate_yolo_nas\wandb\run-20230517_140445-s0fv51bm
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ******
wandb:  View project at https://wandb.ai/******/YOLO-NAS
wandb:  View run at https://wandb.ai/******/YOLO-NAS/runs/s0fv51bm
Train epoch 0: 100%|██████████| 519/519 [04:29<00:00,  1.92it/s, PPYoloELoss/loss=3.55, PPYoloELoss/loss_cls=2.01, PPYoloELoss/loss_dfl=1.65, PPYoloELoss/loss_iou=0.285, gpu_mem=6.74]   
Validation epoch 0: 100%|██████████| 230/230 [01:34<00:00,  2.42it/s]
[2023-05-17 14:11:56] ERROR - sg_trainer_utils.py - Uncaught exception
Traceback (most recent call last):
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 1295, in train
    self._write_to_disk_operations(
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 1669, in _write_to_disk_operations
    self._save_checkpoint(self.optimizer, epoch + 1, validation_results, context)
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 602, in _save_checkpoint
    self.sg_logger.add_checkpoint(tag="ckpt_latest.pth", state_dict=state, global_step=epoch)
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\super_gradients\common\environment\ddp_utils.py", line 64, in wrapper
    return func(*args, **kwargs)
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\super_gradients\common\sg_loggers\wandb_sg_logger.py", line 245, in add_checkpoint
    wandb.save(glob_str=path, base_path=self._local_dir, policy="now")
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 335, in wrapper
    return func(self, *args, **kwargs)
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 1783, in save
    return self._save(glob_str, base_path, policy)
  File "c:\projects\evaluate_yolo_nas\venv\lib\site-packages\wandb\sdk\wandb_run.py", line 1837, in _save
    os.symlink(abs_path, wandb_path)
OSError: [WinError 1314] The client does not possess the requested privilege.: 'C:\\projects\\evaluate_yolo_nas\\checkpoints\\******\\ckpt_latest.pth' -> 'C:\\projects\\evaluate_yolo_nas\\wandb\\run-20230517_140445-s0fv51bm\\files\\ckpt_latest.pth'
`

I have a wandb account and can log in.
How can I resolve this?

**Comment by shaydeci** [comment]
Does this issue persist in the latest SG version for you?
