### ISSUE TITLE
RuntimeError when training with YOLO NAS

### ISSUE THREAD

**Issue by daniqsilva25** [Deci-AI/super-gradients#1079]
Hi,

I have installed super-gradients manually and I'm using it in the docker container _nvcr.io/nvidia/pytorch:22.07-py3_. I've followed [this tutorial](https://learnopencv.com/train-yolo-nas-on-custom-dataset/) on how to train YOLO NAS with a custom dataset, and when the train starts, after the labels are cached and loaded, the following error occurs:

**[2023-05-24 13:13:50] ERROR - sg_trainer_utils.py - Uncaught exception
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    trainer.train(
  File "/root/.local/lib/python3.8/site-packages/super_gradients-3.1.1+master-py3.8.egg/super_gradients/training/sg_trainer/sg_trainer.py", line 1220, in train
    first_batch = next(iter(self.train_loader))
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 475, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/root/.local/lib/python3.8/site-packages/super_gradients-3.1.1+master-py3.8.egg/super_gradients/training/utils/detection_utils.py", line 667, in __call__
    batch = default_collate(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 175, in default_collate
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 175, in <listcomp>
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 149, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 141, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [7, 5] at entry 0 and [6, 5] at entry 1**

I would appreciate some help. Thanks.

**Comment by BloodAxe** [comment]
I'm sorry, but we are not able to provide a technical support for 3rd-party blogposts. 
You either should request the original post author to provide an end-to-end colab notebook or double-check whether you copy-pasted all parts right.

Take a look on our fine-tuning notebook, maybe you will find some differences with what you have: https://colab.research.google.com/drive/1q0RmeVRzLwRXW-h9dPFSOchwJkThUy6d

The error itself telling that number of boxes per image is different during collate, which indicates that padding of bboxes has not been done correctly. Check whether you have [this](https://github.com/Deci-AI/super-gradients/blob/4c2f8c31ac696664efd3809a7896c3f1472217ad/src/super_gradients/recipes/dataset_params/coco_detection_yolo_nas_dataset_params.yaml#L33) or [this](https://github.com/Deci-AI/super-gradients/blob/4c2f8c31ac696664efd3809a7896c3f1472217ad/src/super_gradients/recipes/dataset_params/coco_detection_yolo_nas_dataset_params.yaml#L73) transform.

**Comment by daniqsilva25** [comment]
@BloodAxe thanks for your answer!

I've followed your fine-tuning notebook, and now the following error appears:

**Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/.local/lib/python3.8/site-packages/super_gradients-3.1.0+master-py3.8.egg/super_gradients/training/datasets/detection_datasets/detection_dataset.py", line 346, in __getitem__
    sample = self.apply_transforms(self.get_sample(index))
  File "/root/.local/lib/python3.8/site-packages/super_gradients-3.1.0+master-py3.8.egg/super_gradients/training/datasets/detection_datasets/detection_dataset.py", line 392, in apply_transforms
    sample = transform(sample)
  File "/root/.local/lib/python3.8/site-packages/super_gradients-3.1.0+master-py3.8.egg/super_gradients/training/transforms/transforms.py", line 594, in __call__
    img, target = random_affine(
  File "/root/.local/lib/python3.8/site-packages/super_gradients-3.1.0+master-py3.8.egg/super_gradients/training/transforms/transforms.py", line 1248, in random_affine
    img = cv2.warpAffine(img, M, dsize=target_size, borderValue=(border_value, border_value, border_value))
SystemError: new style getargs format but argument is not a tuple**

Do you know why this is happening?
