### ISSUE TITLE
Export to ONNX problem

### ISSUE THREAD

**Issue by hamedgorji** [Deci-AI/super-gradients#1179]
### 💡 Your Question

Hello,

I trained my model using the custom dataset approach. Then I tried to convert it to ONNX based on your tutorial (https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/YoloNASQuickstart.md). 
(`models.convert_to_onnx(model=net, input_shape=(3,640,640), out_path="yolo_nas_s.onnx")`)

Here is the code I used to convert it to ONNX
```
best_model = models.get('yolo_nas_s',
                        num_classes=len(dataset_params['classes']),
                        checkpoint_path="checkpoints/run-1/ckpt_best.pth")
models.convert_to_onnx(model=best_model, input_shape=(3,320,320), out_path="yolo_nas_s.onnx")
```
But it gives me the following error. Could you please let me how to solve it?

```
[2023-06-15 16:06:02] WARNING - conversion.py - input_shape is deprecated and will be removed in the next major release. Use the input_size kwarg in prep_model_for_conversion_kwargs instead
W0615 16:06:02.394997  6116 conversion.py:85] input_shape is deprecated and will be removed in the next major release. Use the input_size kwarg in prep_model_for_conversion_kwargs instead
C:\Users\Hamed\miniconda3\envs\yoloNAS\lib\site-packages\torch\onnx\symbolic_opset9.py:714: UserWarning: This model contains a squeeze operation on dimension 1. If the model is intended to be used with dynamic input shapes, please use opset version 11 to export the model.
  warnings.warn("This model contains a squeeze operation on dimension " + str(squeeze_dim) + ". If the model is " +
Traceback (most recent call last):
  File "C:\Users\Hamed\miniconda3\envs\yoloNAS\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-82caf4c326f8>", line 1, in <module>
    models.convert_to_onnx(model=best_model, input_shape=(3,320,320), out_path="yolo_nas_s.onnx")
  File "C:\Users\Hamed\miniconda3\envs\yoloNAS\lib\site-packages\super_gradients\common\decorators\factory_decorator.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Hamed\miniconda3\envs\yoloNAS\lib\site-packages\super_gradients\common\decorators\factory_decorator.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Hamed\miniconda3\envs\yoloNAS\lib\site-packages\super_gradients\training\models\conversion.py", line 98, in convert_to_onnx
    onnx_simplify(out_path, out_path)
  File "C:\Users\Hamed\miniconda3\envs\yoloNAS\lib\site-packages\super_gradients\training\models\conversion.py", line 156, in onnx_simplify
    model_sim, check = simplify(model=onnx_path)
  File "C:\Users\Hamed\miniconda3\envs\yoloNAS\lib\site-packages\onnxsim\onnx_simplifier.py", line 199, in simplify
    model_opt_bytes = C.simplify(
  File "C:\Users\Hamed\miniconda3\envs\yoloNAS\lib\site-packages\onnxsim\onnx_simplifier.py", line 260, in Run
    output_arrs = sess.run(output_names, inputs, run_options=run_options)
  File "C:\Users\Hamed\miniconda3\envs\yoloNAS\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: onnx::Concat_1073 Got: 3 Expected: 2 Please fix either the inputs or the model.

```

**Comment by hamedgorji** [comment]
Any comments?

**Comment by naserpiltan** [comment]
@hamedgorji AFA I know, the number of classes argument is also needed, but it seems like you have overlooked it. Try to pass it as well, like this : 
```
models.convert_to_onnx(model=net, input_shape=(3,640,640), out_path="yolo_nas_s.onnx",
    num_classes=1)
``

**Comment by BloodAxe** [comment]
Please specify torch and SG version you are using, since this functionality is covered with tests and proven to work fine with torch 1.9 and higher.
