### ISSUE TITLE
Yolo NAS Finetuning on Roboflow Dataset: error on dataset.get_dataset_preprocessing_params()

### ISSUE THREAD

**Issue by ivan94fi** [Deci-AI/super-gradients#1224]
# Description
I am using a modified version of the YOLO NAS fine [tuning notebook](https://colab.research.google.com/drive/1q0RmeVRzLwRXW-h9dPFSOchwJkThUy6d?usp=sharing) which can be found in https://github.com/Deci-AI/super-gradients/blob/master/YOLONAS.md.

I want to fine tune on a Roboflow 100 dataset, specifically the gauge dataset https://universe.roboflow.com/roboflow-100/gauge-u2lwv/dataset/4#.

# Code

I am using the following code to define the datasets and train the model.

## Imports and dataset definition
```python
import torch
from super_gradients import setup_device
from super_gradients.training import Trainer, dataloaders, models
from super_gradients.training.dataloaders.dataloaders import (
    roboflow_train_yolox,
    roboflow_val_yolox,
)
from super_gradients.training.losses import PPYoloELoss
from super_gradients.training.metrics import DetectionMetrics_050
from super_gradients.training.models.detection_models.pp_yolo_e import (
    PPYoloEPostPredictionCallback,
)

setup_device(
    device="cuda",
    multi_gpu="Off",
    num_gpus=1,
)

CHECKPOINT_DIR = "checkpoints"
trainer = Trainer(experiment_name="my_first_yolonas_run", ckpt_root_dir=CHECKPOINT_DIR)

dataset_params = {
    "data_dir": "/path/to/gauge_dataset",
    "dataset_name": "gauge-u2lwv",
}


dataloader_params = {"batch_size": 16, "num_workers": 4}

train_data = roboflow_train_yolox(
    dataset_params={**dataset_params, "split": "train"},
    dataloader_params={**dataloader_params},
)

valid_data = roboflow_train_yolox(
    dataset_params={**dataset_params, "split": "valid"},
    dataloader_params={**dataloader_params},
)

test_data = roboflow_val_yolox(
    dataset_params={**dataset_params, "split": "test"},
    dataloader_params={**dataloader_params},
)

``` 

## Model definition and training

```python

num_classes = 2

model = models.get("yolo_nas_m", num_classes=num_classes, pretrained_weights="coco")

train_params = {
    "silent_mode": False,
    "average_best_models": True,
    "warmup_mode": "linear_epoch_step",
    "warmup_initial_lr": 1e-6,
    "lr_warmup_epochs": 3,
    "initial_lr": 5e-4,
    "lr_mode": "cosine",
    "cosine_final_lr_ratio": 0.1,
    "optimizer": "Adam",
    "optimizer_params": {"weight_decay": 0.0001},
    "zero_weight_decay_on_bias_and_bn": True,
    "ema": True,
    "ema_params": {"decay": 0.9, "decay_type": "threshold"},
    # ONLY TRAINING FOR 10 EPOCHS FOR THIS EXAMPLE NOTEBOOK
    "max_epochs": 10,
    "mixed_precision": True,
    "loss": PPYoloELoss(
        use_static_assigner=False,
        num_classes=num_classes,
        reg_max=16,
    ),
    "valid_metrics_list": [
        DetectionMetrics_050(
            score_thres=0.1,
            top_k_predictions=300,
            # NOTE: num_classes needs to be defined here
            num_cls=num_classes,
            normalize_targets=True,
            post_prediction_callback=PPYoloEPostPredictionCallback(
                score_threshold=0.01, nms_top_k=1000, max_predictions=300, nms_threshold=0.7
            ),
        )
    ],
    "metric_to_watch": "mAP@0.50",
}

trainer.train(model=model, training_params=train_params, train_loader=train_data, valid_loader=valid_data)

```

# Problem

The dataset and dataloader objects are created, the training process starts, but after one epoch this error message appears (see below for full training output):

```
Traceback (most recent call last):
  File "/home/iprosperi/yolonas/gauge_dataset/intro_to_supergradients_+_yolonas_starter_notebook.py", line 100, in <module>
    trainer.train(model=model, training_params=train_params, train_loader=train_data, valid_loader=valid_data)
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 1288, in train
    self._write_to_disk_operations(
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 1662, in _write_to_disk_operations
    self._save_checkpoint(self.optimizer, epoch + 1, validation_results, context)
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 599, in _save_checkpoint
    state["processing_params"] = self.valid_loader.dataset.get_dataset_preprocessing_params()
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/datasets/detection_datasets/detection_dataset.py", line 498, in get_dataset_preprocessing_params
    pipeline += t.get_equivalent_preprocessing()
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/transforms/transforms.py", line 428, in get_equivalent_preprocessing
    raise NotImplementedError
NotImplementedError
```

<details>
<summary>Complete training output</summary>

```
The console stream is logged into /home/iprosperi/sg_logs/console.log
[2023-06-27 15:02:24] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-06-27 15:02:25] WARNING - sg_trainer.py - Train dataset size % batch_size != 0 and drop_last=False, this might result in smaller last batch.
WARNING: Logging before flag parsing goes to stderr.
W0627 15:02:25.813005 140351798005760 sg_trainer.py:1009] Train dataset size % batch_size != 0 and drop_last=False, this might result in smaller last batch.
The console stream is now moved to checkpoints/my_first_yolonas_run/console_giu27_15_02_28.txt
[2023-06-27 15:02:29] INFO - sg_trainer_utils.py - TRAINING PARAMETERS:
    - Mode:                         OFF
    - Number of GPUs:               1          (1 available on the machine)
    - Dataset size:                 158        (len(train_set))
    - Batch size per GPU:           16         (batch_size)
    - Batch Accumulate:             1          (batch_accumulate)
    - Total batch size:             16         (num_gpus * batch_size)
    - Effective Batch size:         16         (num_gpus * batch_size * batch_accumulate)
    - Iterations per epoch:         32         (len(train_loader))
    - Gradient updates per epoch:   32         (len(train_loader) / batch_accumulate)

[2023-06-27 15:02:29] WARNING - sg_trainer.py - Could not set preprocessing pipeline from the validation dataset:
 .
 Before callingpredict make sure to call set_dataset_processing_params.
[2023-06-27 15:02:29] INFO - sg_trainer.py - Started training for 10 epochs (0/9)

Train epoch 0: 100%|██████████| 32/32 [00:26<00:00,  1.20it/s, PPYoloELoss/loss=3.88, PPYoloELoss/loss_cls=2.85, PPYoloELoss/loss_dfl=1.09, PPYoloELoss/loss_iou=0.197, gpu_mem=10.7]
Validation epoch 0: 100%|██████████| 32/32 [00:34<00:00,  1.08s/it]
===========================================================
SUMMARY OF EPOCH 0
├── Training
│   ├── Ppyoloeloss/loss = 3.8823
│   ├── Ppyoloeloss/loss_cls = 2.8457
│   ├── Ppyoloeloss/loss_dfl = 1.0866
│   └── Ppyoloeloss/loss_iou = 0.1973
└── Validation
    ├── F1@0.50 = 0.0
    ├── Map@0.50 = 0.0327
    ├── Ppyoloeloss/loss = 3.8227
    ├── Ppyoloeloss/loss_cls = 2.9707
    ├── Ppyoloeloss/loss_dfl = 0.9394
    ├── Ppyoloeloss/loss_iou = 0.1529
    ├── Precision@0.50 = 0.0
    └── Recall@0.50 = 0.0

===========================================================
[2023-06-27 15:03:30] INFO - base_sg_logger.py - [CLEANUP] - Successfully stopped system monitoring process
[2023-06-27 15:03:30] ERROR - sg_trainer_utils.py - Uncaught exception
Traceback (most recent call last):
  File "/home/iprosperi/yolonas/gauge_dataset/intro_to_supergradients_+_yolonas_starter_notebook.py", line 100, in <module>
    trainer.train(model=model, training_params=train_params, train_loader=train_data, valid_loader=valid_data)
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 1288, in train
    self._write_to_disk_operations(
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 1662, in _write_to_disk_operations
    self._save_checkpoint(self.optimizer, epoch + 1, validation_results, context)
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 599, in _save_checkpoint
    state["processing_params"] = self.valid_loader.dataset.get_dataset_preprocessing_params()
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/datasets/detection_datasets/detection_dataset.py", line 498, in get_dataset_preprocessing_params
    pipeline += t.get_equivalent_preprocessing()
  File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/transforms/transforms.py", line 428, in get_equivalent_preprocessing
    raise NotImplementedError
NotImplementedError
  Traceback (most recent call last):
    File "/home/iprosperi/yolonas/gauge_dataset/intro_to_supergradients_+_yolonas_starter_notebook.py", line 100, in <module>
      trainer.train(model=model, training_params=train_params, train_loader=train_data, valid_loader=valid_data)
    File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 1288, in train
      self._write_to_disk_operations(
    File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 1662, in _write_to_disk_operations
      self._save_checkpoint(self.optimizer, epoch + 1, validation_results, context)
    File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 599, in _save_checkpoint
      state["processing_params"] = self.valid_loader.dataset.get_dataset_preprocessing_params()
    File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/datasets/detection_datasets/detection_dataset.py", line 498, in get_dataset_preprocessing_params
      pipeline += t.get_equivalent_preprocessing()
    File "/home/iprosperi/yolonas/venv/lib/python3.10/site-packages/super_gradients/training/transforms/transforms.py", line 428, in get_equivalent_preprocessing
      raise NotImplementedError
  NotImplementedError
```

</details>

# Further analysis
The problem is caused by the `DetectionMosaic` transform, defined in https://github.com/Deci-AI/super-gradients/blob/3.1.1/src/super_gradients/training/transforms/transforms.py, which does not override the `get_equivalent_preprocessing()`, so when called it raises the `NotImplementedError`. There might be other transforms that give this problem, but this is certainly one of them.

This transform is included because the functions `super_gradients.training.dataloaders.dataloaders.roboflow_train_yolox` and `super_gradients.training.dataloaders.dataloaders.roboflow_val_yolox` that I use to define the data loaders use the configuration `roboflow_detection_dataset_params.yaml`, which is loaded from https://github.com/Deci-AI/super-gradients/blob/3.1.1/src/super_gradients/recipes/dataset_params/roboflow_detection_dataset_params.yaml
) and includes the following:

```yaml
# ....
train_dataset_params:
  # ...
  transforms:
    - DetectionMosaic:
        input_dim: ${dataset_params.train_dataset_params.input_dim}
        prob: 1.
# ...
```
This error is raised also by just doing one of these:

```python
train_data.dataset.get_dataset_preprocessing_params()
valid_data.dataset.get_dataset_preprocessing_params()
# This actually works -> test_data.dataset.get_dataset_preprocessing_params()
```

# Versions
`super-gradients` version:  `3.1.1`

Other versions:
<details><summary>Details</summary>

```
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-43-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 530.41.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          24
On-line CPU(s) list:             0-23
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 7900X 12-Core Processor
CPU family:                      25
Model:                           97
Thread(s) per core:              2
Core(s) per socket:              12
Socket(s):                       1
Stepping:                        2
Frequency boost:                 enabled
CPU max MHz:                     5732,7139
CPU min MHz:                     3000,0000
BogoMIPS:                        9399.54
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d
Virtualization:                  AMD-V
L1d cache:                       384 KiB (12 instances)
L1i cache:                       384 KiB (12 instances)
L2 cache:                        12 MiB (12 instances)
L3 cache:                        64 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-23
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.13.1
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.14.1
[conda] Could not collect
```

</details>

**Comment by haider10shah** [comment]
I am getting the same issue as well. A suggestion to fix this will be very helpful

**Comment by ivan94fi** [comment]
Hi @haider10shah I am still investigating my issue. I found that using the official recipe to train on roboflow is actually working, even if the datasets object are perfectly the same as in my own code. This is the command that I found is working, and it is taken from https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/YoloNASQuickstart.md#train-on-rf100:

```bash
python3 -m super_gradients.train_from_recipe --config-name=roboflow_yolo_nas_m dataset_name=gauge-u2lwv dataset_params.data_dir=$(pwd)/rf100 ckpt_root_dir=$(pwd)
```

**Comment by ivan94fi** [comment]
Hi everyone, I found an issue with my code.

The validation dataloader should be created with the `roboflow_val_yolox`  function, not with with `roboflow_train_yolox` as I was doing.

This is the correction:
```patch
- valid_data = roboflow_train_yolox(
+ valid_data = roboflow_val_yolox(
    dataset_params={**dataset_params, "split": "valid"},
    dataloader_params={**dataloader_params},
)
```

Closing, as this is not a bug.
