### ISSUE TITLE
import super_gradients Error

### ISSUE THREAD

**Issue by kimtaehyeong** [Deci-AI/super-gradients#1247]
### 💡 Your Question

💡 Your Question
Hello
I installed the package using the following command through the conda virtual environment.
```pip install -r requirements.txt```

After installing normally, if you run ```import super_gradients``` for inference, the following error occurs.
```
The console stream is logged into /home/work/sg_logs/console.log                                                                         
[2023-07-05 13:12:08] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to
 disable it                                                                                                                              
Traceback (most recent call last):                                                                                                       
  File "<stdin>", line 1, in <module>                                                                                                    
  File "/home/work/.conda/envs/yolonas/lib/python3.8/site-packages/super_gradients/__init__.py", line 2, in <module>                     
    from super_gradients.training import losses, utils, datasets_utils, DataAugmentation, Trainer, KDTrainer, QATTrainer                 
  File "/home/work/.conda/envs/yolonas/lib/python3.8/site-packages/super_gradients/training/__init__.py", line 4, in <module>            
    from super_gradients.training.sg_trainer import Trainer                                                                              
  File "/home/work/.conda/envs/yolonas/lib/python3.8/site-packages/super_gradients/training/sg_trainer/__init__.py", line 3, in <module> 
    from super_gradients.training.sg_trainer.sg_trainer import Trainer, MultiGPUMode, StrictLoad                                         
  File "/home/work/.conda/envs/yolonas/lib/python3.8/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 25, in <modul
e>                                
    from super_gradients.common.sg_loggers.abstract_sg_logger import AbstractSGLogger     
  File "/home/work/.conda/envs/yolonas/lib/python3.8/site-packages/super_gradients/common/sg_loggers/__init__.py", line 1, in <module>   
    from super_gradients.common.sg_loggers.base_sg_logger import BaseSGLogger                                                            
  File "/home/work/.conda/envs/yolonas/lib/python3.8/site-packages/super_gradients/common/sg_loggers/base_sg_logger.py", line 21, in <mod
ule>                              
    from super_gradients.common.environment.monitoring import SystemMonitor                                                              
  File "/home/work/.conda/envs/yolonas/lib/python3.8/site-packages/super_gradients/common/environment/monitoring/__init__.py", line 1, in
 <module>                         
    from super_gradients.common.environment.monitoring.monitoring import SystemMonitor                                                   
  File "/home/work/.conda/envs/yolonas/lib/python3.8/site-packages/super_gradients/common/environment/monitoring/monitoring.py", line 5, 
in <module>                       
    from super_gradients.common.environment.monitoring import disk, virtual_memory, network, cpu, gpu                                    
  File "/home/work/.conda/envs/yolonas/lib/python3.8/site-packages/super_gradients/common/environment/monitoring/disk.py", line 5, in <mo
dule>                             
    buffer_io_read_bytes = psutil.disk_io_counters().read_bytes
AttributeError: 'NoneType' object has no attribute 'read_bytes'
```

how can i solve it ?
My package details are as follows

```
# Name                    Version                   Build  Channel                                                              
_libgcc_mutex             0.1                 conda_forge    conda-forge                                                                 
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.4.0                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
cachetools                5.3.1                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi                                                              
flatbuffers               23.5.26                  pypi_0    pypi                                                                        
fonttools                 4.40.0                   pypi_0    pypi                                                                        
future                    0.18.3                   pypi_0    pypi                                                                        
grpcio                    1.56.0                   pypi_0    pypi                                                                        
idna                      3.4                      pypi_0    pypi                                                                        
imagesize                 1.4.1                    pypi_0    pypi                                                                        
importlib-metadata        6.7.0                    pypi_0    pypi                                                                        
importlib-resources       5.12.0                   pypi_0    pypi                                                                        
imutils                   0.5.4                    pypi_0    pypi                                                                        
jinja2                    3.1.2                    pypi_0    pypi                                                                        
jmespath                  1.0.1                    pypi_0    pypi                                                                        
json-tricks               3.16.1                   pypi_0    pypi                                                                        
jsonschema                4.17.3                   pypi_0    pypi                                                                        
kiwisolver                1.4.4                    pypi_0    pypi                                                                        
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge  
idna                      3.4                      pypi_0    pypi                                                              
imagesize                 1.4.1                    pypi_0    pypi                                                                        
importlib-metadata        6.7.0                    pypi_0    pypi                                                                        
importlib-resources       5.12.0                   pypi_0    pypi                                                                        
imutils                   0.5.4                    pypi_0    pypi                                                                        
jinja2                    3.1.2                    pypi_0    pypi                                                                        
jmespath                  1.0.1                    pypi_0    pypi                                                                        
json-tricks               3.16.1                   pypi_0    pypi                                                                        
jsonschema                4.17.3                   pypi_0    pypi                                                                        
kiwisolver                1.4.4                    pypi_0    pypi                                                                        
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge                                                                 
libffi                    3.4.2                h7f98852_5    conda-forge                                                                 
libgcc-ng                 13.1.0               he5830b7_0    conda-forge                                                                 
libgomp                   13.1.0               he5830b7_0    conda-forge                                                                 
libnsl                    2.0.0                h7f98852_0    conda-forge 
libsqlite                 3.42.0               h2797004_0    conda-forge                                                        
libuuid                   2.38.1               h0b41bf4_0    conda-forge                                                                 
libzlib                   1.2.13               hd590300_5    conda-forge                                                                 
markdown                  3.4.3                    pypi_0    pypi                                                                        
matplotlib                3.7.1                    pypi_0    pypi                                                                        
mdurl                     0.1.2                    pypi_0    pypi                                                                        
ncurses                   6.4                  hcb278e6_0    conda-forge                                                                 
numpy                     1.23.0                   pypi_0    pypi                                                                        
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi                                                                        
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi                                                                        
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi                                                                        
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi                                                                        
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.1                     pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi                                                              
pip                       23.1.2             pyhd8ed1ab_0    conda-forge                                                                 
pkgutil-resolve-name      1.3.10                   pypi_0    pypi                                                                        
psutil                    5.9.5                    pypi_0    pypi                                                                        
pyasn1                    0.5.0                    pypi_0    pypi                                                                        
pyasn1-modules            0.3.0                    pypi_0    pypi                                                                        
pycocotools               2.0.4                    pypi_0    pypi                                                                        
pyrsistent                0.19.3                   pypi_0    pypi                                                                        
python                    3.8.17          he550d4f_0_cpython    conda-forge                                                              
python-dateutil           2.8.2                    pypi_0    pypi                                                                        
pytube                    15.0.0                   pypi_0    pypi                                                                        
pytz                      2023.3                   pypi_0    pypi                                                                        
pyyaml                    6.0                      pypi_0    pypi                                                                        
readline                  8.2                  h8228510_1    conda-forge                                                                 
requests                  2.31.0                   pypi_0    pypi 
requests-oauthlib         1.3.1                    pypi_0    pypi                                                             
roboflow                  0.1.1                    pypi_0    pypi                                                                        
rsa                       4.9                      pypi_0    pypi                                                                        
scipy                     1.10.1                   pypi_0    pypi                                                                        
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge                                                                 
six                       1.16.0                   pypi_0    pypi                                                                        
snowballstemmer           2.2.0                    pypi_0    pypi                                                                        
sphinx-rtd-theme          1.2.2                    pypi_0    pypi                                                                        
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi                                                                        
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi                                                                        
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi                                                                        
sphinxcontrib-jquery      4.1                      pypi_0    pypi                                                                        
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi                                                                        
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi                                                                        
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi  
super-gradients           3.1.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
torchinfo                 1.8.0                    pypi_0    pypi
torchvision               0.14.1                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
urllib3                   1.26.16                  pypi_0    pypi
werkzeug                  2.3.6                    pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.15.0                   pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
youtube-dl                2021.12.17               pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
```

**Comment by BloodAxe** [comment]
Hi there ✋ 
I wonder whether your issue is realted to these issues:
https://github.com/giampaolo/psutil/issues/1354
https://github.com/giampaolo/psutil/issues/767

What linux distributive & kernel version are you using?

**Comment by kimtaehyeong** [comment]
Hello! @BloodAxe 
I'm currently using a Conda environment on top of docker.
operating system ```Ubuntu 20.04.5 LTS \n \l```

**Comment by prasadkyp7** [comment]
is there a fix for this, we are also still getting this error

**Comment by ketul93** [comment]
I am also facing the same issue .... 
To my local env it works as expected but while trying to deploy with cloud run it throws the same error 

Here is my `pip freeze`

absl-py==2.1.0
alabaster==0.7.13
albumentations==1.3.1
alembic==1.13.1
antlr4-python3-runtime==4.9.3
arabic-reshaper==3.0.0
asn1crypto==1.5.1
attrs==23.2.0
Babel==2.14.0
backports.zoneinfo==0.2.1
blinker==1.7.0
boto3==1.34.39
botocore==1.34.39
build==1.0.3
cachetools==5.3.2
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
coloredlogs==15.0.1
contourpy==1.1.1
coverage==5.3.1
cryptography==42.0.2
cssselect2==0.7.0
cycler==0.12.1
data-gradients==0.3.2
databricks-cli==0.18.0
Deprecated==1.2.14
docker==6.1.3
docutils==0.17.1
einops==0.3.2
entrypoints==0.4
filelock==3.13.1
Flask==3.0.2
flatbuffers==23.5.26
fonttools==4.48.1
fsspec==2024.2.0
future==0.18.3
gitdb==4.0.11
GitPython==3.1.41
google-api-core==2.17.0
google-auth==2.27.0
google-auth-oauthlib==1.0.0
google-cloud-core==2.4.1
google-cloud-secret-manager==2.12.6
google-cloud-storage==2.7.0
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.62.0
greenlet==3.0.3
grpc-google-iam-v1==0.13.0
grpcio==1.60.1
grpcio-status==1.48.2
gunicorn==21.2.0
html5lib==1.1
humanfriendly==10.0
hydra-core==1.3.2
idna==3.6
imagededup==0.3.2
imageio==2.33.1
imagesize==1.4.1
importlib-metadata==7.0.1
importlib-resources==6.1.1
itsdangerous==2.1.2
Jinja2==3.1.3
jmespath==1.0.1
joblib==1.3.2
json-tricks==3.16.1
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
lazy_loader==0.3
lxml==5.1.0
Mako==1.3.2
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.7.4
mdurl==0.1.2
mlflow==2.9.0
mpmath==1.3.0
networkx==3.1
numpy==1.23.0
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
omegaconf==2.3.0
onnx==1.13.0
onnxruntime==1.13.1
onnxsim==0.4.35
opencv-python==4.9.0.80
opencv-python-headless==4.9.0.80
oscrypto==1.3.0
packaging==23.2
pandas==2.0.3
pillow==10.2.0
pip-tools==7.3.0
pkgutil_resolve_name==1.3.10
platformdirs==4.2.0
proto-plus==1.23.0
protobuf==3.20.3
psutil==5.9.8
psycopg2-binary==2.9.5
pyarrow==14.0.2
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycocotools==2.0.6
pycparser==2.21
pyDeprecate==0.3.2
Pygments==2.17.2
pyHanko==0.21.0
pyhanko-certvalidator==0.26.3
PyJWT==2.8.0
pyparsing==2.4.5
pypdf==4.0.1
pypng==0.20220715.0
pyproject_hooks==1.0.0
python-bidi==0.4.2
python-dateutil==2.8.2
pytz==2023.4
PyWavelets==1.4.1
PyYAML==6.0.1
qrcode==7.4.2
qudida==0.0.4
querystring-parser==1.2.4
rapidfuzz==3.6.1
referencing==0.33.0
reportlab==3.6.13
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.7.0
rpds-py==0.17.1
rsa==4.9
s3transfer==0.10.0
scikit-image==0.21.0
scikit-learn==1.3.2
scipy==1.10.1
seaborn==0.13.2
six==1.16.0
smmap==5.0.1
snowballstemmer==2.2.0
Sphinx==4.0.3
sphinx-rtd-theme==1.3.0
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
SQLAlchemy==2.0.25
sqlparse==0.4.4
stringcase==1.2.0
super-gradients==3.6.0
svglib==1.5.1
sympy==1.12
tabulate==0.9.0
tensorboard==2.14.0
tensorboard-data-server==0.7.2
termcolor==1.1.0
threadpoolctl==3.2.0
tifffile==2023.7.10
tinycss2==1.2.1
tomli==2.0.1
torch==2.2.0
torchmetrics==0.8.0
torchvision==0.17.0
tqdm==4.66.1
treelib==1.6.1
triton==2.2.0
typing_extensions==4.9.0
tzdata==2023.4
tzlocal==5.2
uritools==4.0.2
urllib3==1.26.18
webencodings==0.5.1
websocket-client==1.7.0
Werkzeug==3.0.1
wrapt==1.16.0
xhtml2pdf==0.2.11
zipp==3.17.0

**Comment by gh-wf** [comment]
> I am also facing the same issue .... To my local env it works as expected but while trying to deploy with cloud run it throws the same error
> 
> Here is my `pip freeze`
> 
> absl-py==2.1.0 alabaster==0.7.13 albumentations==1.3.1 alembic==1.13.1 antlr4-python3-runtime==4.9.3 arabic-reshaper==3.0.0 asn1crypto==1.5.1 attrs==23.2.0 Babel==2.14.0 backports.zoneinfo==0.2.1 blinker==1.7.0 boto3==1.34.39 botocore==1.34.39 build==1.0.3 cachetools==5.3.2 certifi==2024.2.2 cffi==1.16.0 charset-normalizer==3.3.2 click==8.1.7 cloudpickle==3.0.0 coloredlogs==15.0.1 contourpy==1.1.1 coverage==5.3.1 cryptography==42.0.2 cssselect2==0.7.0 cycler==0.12.1 data-gradients==0.3.2 databricks-cli==0.18.0 Deprecated==1.2.14 docker==6.1.3 docutils==0.17.1 einops==0.3.2 entrypoints==0.4 filelock==3.13.1 Flask==3.0.2 flatbuffers==23.5.26 fonttools==4.48.1 fsspec==2024.2.0 future==0.18.3 gitdb==4.0.11 GitPython==3.1.41 google-api-core==2.17.0 google-auth==2.27.0 google-auth-oauthlib==1.0.0 google-cloud-core==2.4.1 google-cloud-secret-manager==2.12.6 google-cloud-storage==2.7.0 google-crc32c==1.5.0 google-resumable-media==2.7.0 googleapis-common-protos==1.62.0 greenlet==3.0.3 grpc-google-iam-v1==0.13.0 grpcio==1.60.1 grpcio-status==1.48.2 gunicorn==21.2.0 html5lib==1.1 humanfriendly==10.0 hydra-core==1.3.2 idna==3.6 imagededup==0.3.2 imageio==2.33.1 imagesize==1.4.1 importlib-metadata==7.0.1 importlib-resources==6.1.1 itsdangerous==2.1.2 Jinja2==3.1.3 jmespath==1.0.1 joblib==1.3.2 json-tricks==3.16.1 jsonschema==4.21.1 jsonschema-specifications==2023.12.1 kiwisolver==1.4.5 lazy_loader==0.3 lxml==5.1.0 Mako==1.3.2 Markdown==3.5.2 markdown-it-py==3.0.0 MarkupSafe==2.1.5 matplotlib==3.7.4 mdurl==0.1.2 mlflow==2.9.0 mpmath==1.3.0 networkx==3.1 numpy==1.23.0 nvidia-cublas-cu12==12.1.3.1 nvidia-cuda-cupti-cu12==12.1.105 nvidia-cuda-nvrtc-cu12==12.1.105 nvidia-cuda-runtime-cu12==12.1.105 nvidia-cudnn-cu12==8.9.2.26 nvidia-cufft-cu12==11.0.2.54 nvidia-curand-cu12==10.3.2.106 nvidia-cusolver-cu12==11.4.5.107 nvidia-cusparse-cu12==12.1.0.106 nvidia-nccl-cu12==2.19.3 nvidia-nvjitlink-cu12==12.3.101 nvidia-nvtx-cu12==12.1.105 oauthlib==3.2.2 omegaconf==2.3.0 onnx==1.13.0 onnxruntime==1.13.1 onnxsim==0.4.35 opencv-python==4.9.0.80 opencv-python-headless==4.9.0.80 oscrypto==1.3.0 packaging==23.2 pandas==2.0.3 pillow==10.2.0 pip-tools==7.3.0 pkgutil_resolve_name==1.3.10 platformdirs==4.2.0 proto-plus==1.23.0 protobuf==3.20.3 psutil==5.9.8 psycopg2-binary==2.9.5 pyarrow==14.0.2 pyasn1==0.5.1 pyasn1-modules==0.3.0 pycocotools==2.0.6 pycparser==2.21 pyDeprecate==0.3.2 Pygments==2.17.2 pyHanko==0.21.0 pyhanko-certvalidator==0.26.3 PyJWT==2.8.0 pyparsing==2.4.5 pypdf==4.0.1 pypng==0.20220715.0 pyproject_hooks==1.0.0 python-bidi==0.4.2 python-dateutil==2.8.2 pytz==2023.4 PyWavelets==1.4.1 PyYAML==6.0.1 qrcode==7.4.2 qudida==0.0.4 querystring-parser==1.2.4 rapidfuzz==3.6.1 referencing==0.33.0 reportlab==3.6.13 requests==2.31.0 requests-oauthlib==1.3.1 rich==13.7.0 rpds-py==0.17.1 rsa==4.9 s3transfer==0.10.0 scikit-image==0.21.0 scikit-learn==1.3.2 scipy==1.10.1 seaborn==0.13.2 six==1.16.0 smmap==5.0.1 snowballstemmer==2.2.0 Sphinx==4.0.3 sphinx-rtd-theme==1.3.0 sphinxcontrib-applehelp==1.0.4 sphinxcontrib-devhelp==1.0.2 sphinxcontrib-htmlhelp==2.0.1 sphinxcontrib-jquery==4.1 sphinxcontrib-jsmath==1.0.1 sphinxcontrib-qthelp==1.0.3 sphinxcontrib-serializinghtml==1.1.5 SQLAlchemy==2.0.25 sqlparse==0.4.4 stringcase==1.2.0 super-gradients==3.6.0 svglib==1.5.1 sympy==1.12 tabulate==0.9.0 tensorboard==2.14.0 tensorboard-data-server==0.7.2 termcolor==1.1.0 threadpoolctl==3.2.0 tifffile==2023.7.10 tinycss2==1.2.1 tomli==2.0.1 torch==2.2.0 torchmetrics==0.8.0 torchvision==0.17.0 tqdm==4.66.1 treelib==1.6.1 triton==2.2.0 typing_extensions==4.9.0 tzdata==2023.4 tzlocal==5.2 uritools==4.0.2 urllib3==1.26.18 webencodings==0.5.1 websocket-client==1.7.0 Werkzeug==3.0.1 wrapt==1.16.0 xhtml2pdf==0.2.11 zipp==3.17.0

Did you ever get your issue resolved?  I'm having the same problem.  I can run my local docker container fine, but when deploying to Google Cloud Run I get this error.

**Comment by gh-wf** [comment]
I was able to fix the error.  I forked the repo and made an update, it now works on Google cloud run.

I'll look into the process to contribute an update to the main repo text week.
