### ISSUE TITLE
Number of model parameters

### ISSUE THREAD

**Issue by AlexeyDate** [Deci-AI/super-gradients#1299]
### 💡 Your Question

I try to print number of model parameters using torchsummary, but I have a some error.
How can I print the total number of parameters of my model?

### Versions
super-gradients==3.1.2

_No response_

**Comment by BloodAxe** [comment]
To help you with **some error** you may want to attach **some output logs**.

**Comment by AlexeyDate** [comment]
> In order to let us help you with **some error** you may want to attach **some output logs**.

I use the following command: **print(summary(model=model, input_size=(3, 320, 320), batch_size=16, device='cpu'))**

Traceback (most recent call last):
  File "/home/teo/programming/Internship/architectures_comparison/YOLO-NAS/yolo_nas.py", line 144, in <module>
    print(summary(model=model, input_size=(3, 320, 320), batch_size=16, device='cpu'))
  File "/home/teo/programming/Internship/architectures_comparison/YOLO-NAS/venv/lib/python3.9/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/teo/programming/Internship/architectures_comparison/YOLO-NAS/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/teo/programming/Internship/architectures_comparison/YOLO-NAS/venv/lib/python3.9/site-packages/super_gradients/training/models/detection_models/customizable_detector.py", line 88, in forward
    x = self.neck(x)
  File "/home/teo/programming/Internship/architectures_comparison/YOLO-NAS/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/teo/programming/Internship/architectures_comparison/YOLO-NAS/venv/lib/python3.9/site-packages/super_gradients/training/models/detection_models/yolo_nas/panneck.py", line 59, in forward
    x_n1_inter, x = self.neck1([c5, c4, c3])
  File "/home/teo/programming/Internship/architectures_comparison/YOLO-NAS/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "/home/teo/programming/Internship/architectures_comparison/YOLO-NAS/venv/lib/python3.9/site-packages/torchsummary/torchsummary.py", line 19, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
AttributeError: 'list' object has no attribute 'size'
