### ISSUE TITLE
Tensorboard save model graph

### ISSUE THREAD

**Issue by Yue-Rain** [Deci-AI/super-gradients#1328]
### 💡 Your Question

i want to use tensorboard to show YOLONAS-S model graph,and add two lines code in super-gradients\src\super_gradients\training\sg_trainer\sg_trainer.py
and met an error.

YOLONAS-M configuration:
load_checkpoint: False
resume: False

dataset_params:
  train_dataloader_params:
    batch_size: 16

arch_params:
  num_classes: 2

training_hyperparams:
  resume: ${resume}
  mixed_precision: True

architecture: yolo_nas_m

multi_gpu: DDP
num_gpus: 8

here is the error message:
Default process group has not been initialized, please make sure to call init_process_group.
Error occurs, No graph saved
Error executing job with overrides: ['num_gpus=2']
Traceback (most recent call last):
  File "src/super_gradients/train_from_recipe.py", line 20, in _main
    Trainer.train_from_config(cfg)
  File "super-gradients-master/src/super_gradients/training/sg_trainer/sg_trainer.py", line 280, in train_from_config
    additional_configs_to_log=recipe_logged_cfg,
  File "super-gradients-master/src/super_gradients/training/sg_trainer/sg_trainer.py", line 1476, in train
    self.sg_logger.add_model_graph("yolonas-m",self.net,inputs)
  File "super-gradients-master/src/super_gradients/common/environment/ddp_utils.py", line 64, in wrapper
    return func(*args, **kwargs)
  File "super-gradients-master/src/super_gradients/common/sg_loggers/base_sg_logger.py", line 232, in add_model_graph
    self.tensorboard_writer.add_graph(model=model, input_to_model=dummy_input)
  File ".local/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 841, in add_graph
    graph(model, input_to_model, verbose, use_strict_trace)
  File ".local/lib/python3.7/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 343, in graph
    raise e
  File ".local/lib/python3.7/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 337, in graph
    trace = torch.jit.trace(model, args, strict=use_strict_trace)
  File ".local/lib/python3.7/site-packages/torch/jit/_trace.py", line 768, in trace
    _module_class,
  File ".local/lib/python3.7/site-packages/torch/jit/_trace.py", line 960, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File ".local/lib/python3.7/site-packages/torch/jit/_trace.py", line 574, in make_module
    elif torch._jit_internal.module_has_exports(mod):
  File ".local/lib/python3.7/site-packages/torch/_jit_internal.py", line 749, in module_has_exports
    if hasattr(mod, name):
  File ".local/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1698, in _distributed_rank
    return dist.get_rank(self.process_group)
  File ".local/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1044, in get_rank
    default_pg = _get_default_group()
  File ".local/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 585, in _get_default_group
    "Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2023-07-27 15:15:29,441][torch.distributed.elastic.multiprocessing.api][ERROR] - failed (exitcode: 1) local_rank: 0 (pid: 52630) of binary: /opt/conda/bin/python
Error executing job with overrides: ['num_gpus=2']
Traceback (most recent call last):
  File "src/super_gradients/train_from_recipe.py", line 20, in _main
    Trainer.train_from_config(cfg)
  File "super-gradients-master/src/super_gradients/training/sg_trainer/sg_trainer.py", line 236, in train_from_config
    num_gpus=core_utils.get_param(cfg, "num_gpus"),
  File "super-gradients-master/src/super_gradients/common/decorators/factory_decorator.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "super-gradients-master/src/super_gradients/training/utils/distributed_training_utils.py", line 240, in setup_device
    setup_gpu(multi_gpu, num_gpus)
  File "super-gradients-master/src/super_gradients/training/utils/distributed_training_utils.py", line 278, in setup_gpu
    restart_script_with_ddp(num_gpus=num_gpus)
  File ".local/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "super-gradients-master/src/super_gradients/training/utils/distributed_training_utils.py", line 387, in restart_script_with_ddp
    elastic_launch(config=config, entrypoint=sys.executable)(*sys.argv, *EXTRA_ARGS)
  File ".local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File ".local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/super_gradients/train_from_recipe.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-27_15:15:29
  host      : jupyter-95ab5b41d9c66d2c-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 52630)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
anyone met the same problem?what should i do?

```
def train(
        self,
        model: nn.Module,
        training_params: dict = None,
        train_loader: DataLoader = None,
        valid_loader: DataLoader = None,
        test_loaders: Dict[str, DataLoader] = None,
        additional_configs_to_log: Dict = None,
    ):  
        #......
        finally:
               if device_config.multi_gpu == MultiGPUMode.DISTRIBUTED_DATA_PARALLEL:
                    # CLEAN UP THE MULTI-GPU PROCESS GROUP WHEN DONE
                    if torch.distributed.is_initialized() and self.training_params.kill_ddp_pgroup_on_end:
                        torch.distributed.destroy_process_group()

                   # PHASE.TRAIN_END
                   self.phase_callback_handler.on_training_end(context)

                   if not self.ddp_silent_mode:
                        # three lines added
                        self.sg_logger.add_model_graph("yolonas-m",self.net,inputs)
                        self.sg_logger.add_images("yolonas-m",inputs,global_step=0)
                        self.sg_logger.upload()
                
                        self.sg_logger.close()
```

**Comment by BloodAxe** [comment]
You problem likes quite deep.
If you are training with DDP, you should not destroy process group, because `self.net` is a still wrapped with `DistributedDataParallel`. It is important since `add_model_graph` runs forward() to capture the graph. And since you destroyed the process group it obviously crash.

To me the right way to do this loggig would be to write the custom callback that would log the model graph at the start of training (On first batch of the first epoch).

Or, your always can export model to ONNX and visualize it with Netron.
