### ISSUE TITLE
Encountering Issue with Latest Super Gradients and torch_compile

### ISSUE THREAD

**Issue by sunmooncode** [Deci-AI/super-gradients#1372]
### 💡 Your Question

I would like to use the parameter torch_compile, but I am encountering the following error when using the latest version. However, the error does not occur when using version 3.1.2.
`
[2023-08-14 17:04:55] INFO - sg_trainer.py - Started training for 300 epochs (0/299)

Train epoch 0:   0%|          | 0/7450 [00:00<?, ?it/s]Error executing job with overrides: []
Error executing job with overrides: []
Traceback (most recent call last):
  File "main.py", line 16, in _main
    Trainer.train_from_config(cfg)
  File "/home/archie/anaconda3/envs/yolonas/lib/python3.8/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 274, in train_from_config
    res = trainer.train(
  File "/home/archie/anaconda3/envs/yolonas/lib/python3.8/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 1361, in train
    train_metrics_tuple = self._train_epoch(context=context, silent_mode=silent_mode)
  File "/home/archie/anaconda3/envs/yolonas/lib/python3.8/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 434, in _train_epoch
    self.phase_callback_handler.on_train_batch_start(context)
  File "/home/archie/anaconda3/envs/yolonas/lib/python3.8/site-packages/super_gradients/training/utils/callbacks/base_callbacks.py", line 465, in on_train_batch_start
    callback.on_train_batch_start(context)
  File "/home/archie/anaconda3/envs/yolonas/lib/python3.8/site-packages/super_gradients/training/utils/callbacks/callbacks.py", line 359, in on_train_batch_start
    self.update_lr(context.optimizer, context.epoch, context.batch_idx)
  File "/home/archie/anaconda3/envs/yolonas/lib/python3.8/site-packages/super_gradients/training/utils/callbacks/callbacks.py", line 370, in update_lr
    param_groups = unwrap_model(self.net).update_param_groups(
  File "/home/archie/anaconda3/envs/yolonas/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 79, in __getattr__
    return getattr(self._orig_mod, name)
  File "/home/archie/anaconda3/envs/yolonas/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'update_param_groups'`

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00)  [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3080 Ti
GPU 1: NVIDIA GeForce RTX 3080 Ti
GPU 2: NVIDIA GeForce RTX 3080 Ti
GPU 3: NVIDIA GeForce RTX 3080 Ti

Nvidia driver version: 525.125.06
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          20
On-line CPU(s) list:             0-19
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
Stepping:                        7
CPU MHz:                         1200.020
CPU max MHz:                     4700.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        7399.70
Virtualization:                  VT-x
L1d cache:                       320 KiB
L1i cache:                       320 KiB
L2 cache:                        10 MiB
L3 cache:                        19.3 MiB
NUMA node0 CPU(s):               0-19
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==4.0.1
[pip3] numpy==1.23.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torchaudio                2.0.1+cu118              pypi_0    pypi
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchvision               0.15.1+cu118             pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

**Comment by BloodAxe** [comment]
Can you please provide what training recipe are you running and whether you are running train from command line or from Jupyter?

**Comment by sunmooncode** [comment]
@BloodAxe Thank you for your reply. Here are the script and configuration files that I will be using for training purposes.


`"""
Entry point for training from a recipe using SuperGradients.

General use: python -m super_gradients.train_from_recipe --config-name="DESIRED_RECIPE".
For recipe's specific instructions and details refer to the recipe's configuration file in the recipes directory.
"""

from omegaconf import DictConfig
import hydra

from super_gradients import Trainer, init_trainer


@hydra.main(config_path="src/super_gradients/recipes", config_name= "test", version_base="1.2")
def _main(cfg: DictConfig) -> None:
    Trainer.train_from_config(cfg)


def main() -> None:
    init_trainer()  # `init_trainer` needs to be called before `@hydra.main`
    _main()


if __name__ == "__main__":
    main()`



`defaults:
  - training_hyperparams: coco2017_yolo_nas_train_params
  - dataset_params: coco_detection_yolo_format_base_dataset_params
  - arch_params: yolo_nas_m_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

train_dataloader: coco_detection_yolo_format_train
val_dataloader: coco_detection_yolo_format_val

load_checkpoint: True
resume: False

dataset_params:
  train_dataloader_params:
    batch_size: 8
    num_workers: 4
  
  val_dataloader_params:
    batch_size: 8
    num_workers: 2

arch_params:
  num_classes: 30

training_hyperparams:
  resume: ${resume}
  mixed_precision: True
  torch_compile: True
  torch_compile_mode: default | reduce-overhead | max-autotune
  ema: False
  sync_bn: False

architecture: yolo_nas_m

multi_gpu: DDP
num_gpus: 4

experiment_suffix: ""
experiment_name: test_${architecture}${experiment_suffix}
`

**Comment by BloodAxe** [comment]
Thanks, we will check whether we can reproduce the issue.
Just want to double-check, isn't there a typo in `torch_compile_mode: default | reduce-overhead | max-autotune` ?

**Comment by sunmooncode** [comment]
`torch_compile_mode: default | reduce-overhead | max-autotune` from [here](https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/ImprovingTrainingTime.md#:~:text=torch_compile_mode%3A%20default%20%7C%20reduce%2Doverhead%20%7C%20max%2Dautotune).

**Comment by BloodAxe** [comment]
Ok, maybe docs was not clear as I though. `default | reduce-overhead | max-autotune` mean one may choose one option: `default` or `reduce-overhead` or `max-autotune``:

```
torch_compile_mode: default 
```

Can you please check whether this helps your issue, since this seems the only difference from what we were using for benchmarking/testing this feature.

**Comment by sunmooncode** [comment]
When I modify the `torch_compile_mode` to `default`, I encounter the same error in version 3.1.3 but not in version 3.1.2.
