### ISSUE TITLE
AttributeError: 'YoloHead' object has no attribute 'anchors'

### ISSUE THREAD

**Issue by gsrujana** [Deci-AI/super-gradients#1434]
### 🐛 Describe the bug

Getting this error when trying to fine-tune yolox model on version 3.2.0. This is issue with any of the yolox - l,s etc. No issues on using version 3.1.3.
`[2023-08-30 21:02:03] INFO - checkpoint_utils.py - Successfully loaded pretrained weights for architecture yolox_l
Traceback (most recent call last):
  File "/home/ubuntu/EFSDrive/Users/sgattupa/workspace/cxrs_greeniq/third_party/training_yoloX/train.py", line 40, in <module>
    model = models.get(MODEL_ARCH, num_classes=107, pretrained_weights="coco").to(DEVICE)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/super_gradients/training/models/model_factory.py", line 222, in get
    net = instantiate_model(model_name, arch_params, checkpoint_num_classes, pretrained_weights, download_required_code)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/super_gradients/training/models/model_factory.py", line 162, in instantiate_model
    net.replace_head(new_num_classes=num_classes_new_head)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/super_gradients/training/models/detection_models/yolo_base.py", line 684, in replace_head
    stride=self._head.anchors.stride,
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'YoloHead' object has no attribute 'anchors'`

### Versions

3.2.0

**Comment by Louis-Dupont** [comment]
Hi @gsrujana ,
This is a known issue that was recently addressed in this PR https://github.com/Deci-AI/super-gradients/pull/1411
It will be part of the next release `3.2.1` which should come pretty soon

**Comment by BloodAxe** [comment]
Fixed in [3.2.1](https://github.com/Deci-AI/super-gradients/releases/tag/3.2.1) release.
