### ISSUE TITLE
YoloNAS with dynamic input shape

### ISSUE THREAD

**Issue by kevinzezel** [Deci-AI/super-gradients#1454]
### 💡 Your Question

I'm not able to convert the model to onnx with dynamic input shape.

```
from super_gradients.training import models
net = models.get("yolo_nas_s", pretrained_weights="coco")
models.convert_to_onnx(model=net, input_shape=(3,640,640), out_path="yolo_nas_s.onnx")
```

Is there any flag I can put in the above code?

I tried to convert using the ultralytics package, but without success. Only works with yolov8.

`yolo task=detect mode=export model=yolo_nas_s.pt format=onnx dynamic=True`
```
The console stream is logged into /root/sg_logs/console.log
[2023-09-08 04:54:41] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/cfg/__init__.py", line 420, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/model.py", line 92, in __init__
    self._load(model, task)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/model.py", line 138, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 589, in attempt_load_one_weight
    args = {**DEFAULT_CFG_DICT, **(ckpt.get('train_args', {}))}  # combine model and default args, preferring model args
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'YoloNAS_S' object has no attribute 'get'
```

Regards,
Kevin

**Comment by BloodAxe** [comment]
Starting from 3.2.0 release (Although we already have 3.2.1 which I suggest to use), you can
export YoloNAS to ONNX format with a simple call:
```
net = models.get("yolo_nas_s", pretrained_weights="coco")
net.export("yolo_nas_s.onnx").
```

This would export model with preprocessing (Normalization) and postprocessing (Decoding & NMS). Additional documentation about this method is available [here](https://docs.deci.ai/super-gradients/latest/documentation/source/models_export.html), [here](https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/examples/model_export/models_export.ipynb) and [here](https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/module_interfaces/exportable_detector.py#L139)

Please note that exporting a model with dynamic shape of the input is **not supported** as the moment.

**Comment by manoj-samal** [comment]
yolo predict model=yolo_nas_s.pt source=/home/input_videos
 
 same error put i was tyring with yolov8 any idea how to fix this 
 

The console stream is logged into /root/sg_logs/console.log
[2023-11-22 14:40:46] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-11-22 14:40:46] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-11-22 14:40:48] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-11-22 14:40:48] WARNING - export.py - Failed to import pytorch_quantization
[2023-11-22 14:40:48] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-11-22 14:40:48] INFO - env_sanity_check.py - Library check is not supported when super_gradients installed through "git+https://github.com/..." command
Traceback (most recent call last):
  File "/home/TCL_env/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 419, in entrypoint
    model = YOLO(model, task=task)
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/engine/model.py", line 97, in __init__
    self._load(model, task)
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/engine/model.py", line 149, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/TCL_env/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 629, in attempt_load_one_weight
    args = {**DEFAULT_CFG_DICT, **(ckpt.get('train_args', {}))}  # combine model and default args, preferring model args
  File "/home/TCL_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'YoloNAS_S' object has no attribute 'get'
