### ISSUE TITLE
What's the dependencies for the installation on Windows super-gradients pakaces healty?

### ISSUE THREAD

**Issue by mahmutakyol** [Deci-AI/super-gradients#1487]
### 💡 Your Question

Hi, I'm trying to install `super-gradient` on my windows11 PC and see lots off errors or  warnings like below. 

P.S: Installed Packages like this 
```bash
! pip install Cython
! pip install cmake
! pip install pycocotools
! pip install wheel
! pip install onnx
! pip install super-gradients
```

```bash
 error: subprocess-exited-with-error
  
  Building wheel for pycocotools (pyproject.toml) did not run successfully.
  exit code: 1
  
  [25 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-cpython-311\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-311\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-cpython-311\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-311\pycocotools
  running build_ext
  C:\Users\PC\AppData\Local\Temp\pip-build-env-dqtrbhrr\overlay\Lib\site-packages\Cython\Compiler\Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\PC\AppData\Local\Temp\pip-install-ekvx6giq\pycocotools_3b2356fe81ba4c929a379bbe4495c411\pycocotools\_mask.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  Compiling pycocotools/_mask.pyx because it changed.
  [1/1] Cythonizing pycocotools/_mask.pyx
  building 'pycocotools._mask' extension
  creating build\temp.win-amd64-cpython-311
  creating build\temp.win-amd64-cpython-311\common
  creating build\temp.win-amd64-cpython-311\Release
  creating build\temp.win-amd64-cpython-311\Release\common
  creating build\temp.win-amd64-cpython-311\Release\pycocotools
  "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\PC\AppData\Local\Temp\pip-build-env-dqtrbhrr\overlay\Lib\site-packages\numpy\core\include -I./common -IC:\Users\PC\anaconda3\include -IC:\Users\PC\anaconda3\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-cpython-311\Release\../common/maskApi.obj
  maskApi.c
  c1: fatal error C1083: Cannot open source file: '../common/maskApi.c': No such file or directory
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
  error: subprocess-exited-with-error
  
  Building wheel for onnx (pyproject.toml) did not run successfully.
  exit code: 1
  
  [72 lines of output]
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Using cmake args: ['C:\\Users\\PC\\anaconda3\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\PC\\anaconda3\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\PC\\anaconda3\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp311-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.11', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ekvx6giq\\onnx_7fd841a6af7c4353b5b0d5d071b5844d']
  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "C:\Users\PC\anaconda3\Scripts\cmake.exe\__main__.py", line 4, in <module>
  ModuleNotFoundError: No module named 'cmake'
  Traceback (most recent call last):
    File "C:\Users\PC\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\PC\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
      return self._build_with_temp_dir(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 332, in <module>
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
      super().run_command(command)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
      self.run_command("build")
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
      super().run_command(command)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
      super().run_command(command)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "<string>", line 223, in run
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
      super().run_command(command)
    File "C:\Users\PC\AppData\Local\Temp\pip-build-env-6pvypf56\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "<string>", line 209, in run
    File "C:\Users\PC\anaconda3\Lib\subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\PC\\anaconda3\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\PC\\anaconda3\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\PC\\anaconda3\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp311-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.11', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ekvx6giq\\onnx_7fd841a6af7c4353b5b0d5d071b5844d']' returned non-zero exit status 1.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
ERROR: Could not build wheels for pycocotools, onnx, which is required to install pyproject.toml-based projects
```

**Comment by BloodAxe** [comment]
The issue you are experiencing comes from `pycocotools==2.0.6` that requires compilation of some native code. On Windows it requires you to have VC Compile tools installed. As brief googling suggests - this is fairly common and known nuance: https://stackoverflow.com/questions/70726826/could-not-install-pycocotools-in-windows10
Once you able to install pycocotools using suggested solution the rest should install smoothly.
