### ISSUE TITLE
Importing super gradients is failing on Torch 2.0

### ISSUE THREAD

**Issue by prasadkyp7** [Deci-AI/super-gradients#1538]
### 🐛 Describe the bug

While importing the supergradients using super_gradients on torch 2.0 , its giving an error that torch distributed is missing . the error is shown below. Looks like some code has to removed and not yet done. 

import super_gradients
The console stream is logged into /root/sg_logs/console.log
[2023-10-17 02:35:45] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-10-17 02:35:45] WARNING - __init__.py - Failed to import pytorch_quantization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/super_gradients/__init__.py", line 4, in <module>
    from super_gradients.training import losses, utils, datasets_utils, DataAugmentation, Trainer, KDTrainer, QATTrainer
  File "/usr/local/lib/python3.8/dist-packages/super_gradients/training/__init__.py", line 2, in <module>
    import super_gradients.training.utils.distributed_training_utils as distributed_training_utils
  File "/usr/local/lib/python3.8/dist-packages/super_gradients/training/utils/__init__.py", line 10, in <module>
    from super_gradients.training.utils.checkpoint_utils import adapt_state_dict_to_fit_model_layer_names, raise_informative_runtime_error
  File "/usr/local/lib/python3.8/dist-packages/super_gradients/training/utils/checkpoint_utils.py", line 16, in <module>
    from super_gradients.training.utils.distributed_training_utils import wait_for_the_master
  File "/usr/local/lib/python3.8/dist-packages/super_gradients/training/utils/distributed_training_utils.py", line 12, in <module>
    from torch.distributed import get_rank, all_gather_object
ImportError: cannot import name 'get_rank' from 'torch.distributed' (/usr/local/lib/python3.8/dist-packages/torch/distributed/__init__.py)

### Versions

python version 3.8.10
cuda 11.4
OS - Ubuntu linux 20.04

Python versions shown below

onnx==1.13.0
onnx-simplifier==0.3.10

torch==2.0.0a0+ec3941ad.nv23.2

torchvision==0.14.1a0+5e8e2f1

**Comment by BloodAxe** [comment]
`2.0.0a0+ec3941ad.nv23.2` - is it nightly build?
I can stay using stable torch 2.0 & 2.0.1 works perfectly well with SG. I'm on 3.3.1 but 3.3.0 and 3.2 should also work fine.
