### ISSUE TITLE
CoCoSegmentationDataSet.__init__() missing 1 required positional argument: 'root_dir'

### ISSUE THREAD

**Issue by Bananaspirit** [Deci-AI/super-gradients#1553]
### 🐛 Describe the bug

Hi! Thank you so much for the work done!

I want to connect the COCO dataset, for this I found a [class](https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/training/datasets/segmentation_datasets/coco_segmentation.py#L25) that allows me to do this. It describes the following scheme, including instructions on how to connect data. However, the instruction does not correspond to what is described in the class, which is why an error occurs.
Tell me, what is the problem?

scheme: 
```
Segmentation Data Set Class for COCO 2017 Segmentation Data Set

    To use this Dataset you need to:

        - Download coco dataset:
            annotations: http://images.cocodataset.org/annotations/annotations_trainval2017.zip
            train2017: http://images.cocodataset.org/zips/train2017.zip
            val2017: http://images.cocodataset.org/zips/val2017.zip

        - Unzip and organize it as below:
            coco
            ├── annotations
            │      ├─ instances_train2017.json
            │      ├─ instances_val2017.json
            │      └─ ...
            └── images
                ├── train2017
                │   ├─ 000000000001.jpg
                │   └─ ...
                └── val2017
                    └─ ...

        - Instantiate the dataset:
            >> train_set = CoCoSegmentationDataSet(data_dir='.../coco', subdir='images/train2017', json_file='instances_train2017.json', ...)
            >> valid_set = CoCoSegmentationDataSet(data_dir='.../coco', subdir='images/val2017', json_file='instances_val2017.json', ...)
```
my code:
```python
train_set = CoCoSegmentationDataSet(data_dir='/content/drive/MyDrive/RSM_data/coco', subdir='images/train2017', json_file='instances_train2017.json')
valid_set = CoCoSegmentationDataSet(data_dir='/content/drive/MyDrive/RSM_data/coco', subdir='images/val2017', json_file='instances_val2017.json')
```
my error:
```sh
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-30-7afcb13a3784>](https://localhost:8080/#) in <cell line: 1>()
----> 1 train_set = CoCoSegmentationDataSet(data_dir='/content/drive/MyDrive/RSM_data/coco', subdir='images/train2017', json_file='instances_train2017.json')
      2 valid_set = CoCoSegmentationDataSet(data_dir='/content/drive/MyDrive/RSM_data/coco', subdir='images/val2017', json_file='instances_val2017.json')

TypeError: CoCoSegmentationDataSet.__init__() missing 1 required positional argument: 'root_dir'
```

### Versions

```
CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        55 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.13.0
[pip3] onnx-simplifier==0.4.33
[pip3] onnxruntime==1.13.1
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchmetrics==0.8.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect
```

**Comment by Louis-Dupont** [comment]
Hi @Bananaspirit,
It looks like the docstring is not right, we will fix this very soon.
Based on your code, I think this should work:

```python
train_set = CoCoSegmentationDataSet(root_dir='/content/drive/MyDrive/RSM_data/coco', samples_sub_directory='images/train2017', targets_sub_directory='annotations', list_file='instances_train2017.json')

valid_set = CoCoSegmentationDataSet(root_dir='/content/drive/MyDrive/RSM_data/coco', samples_sub_directory='images/val2017', targets_sub_directory='annotations', list_file='instances_val2017.json')
```

**Comment by Bananaspirit** [comment]
@Louis-Dupont This solved my download problem, thank you for your help. However, another problem has arisen that I have not been able to solve for a long time...
```bash
The console stream is logged into /home/banana/sg_logs/console.log
[2023-11-17 13:28:46] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-11-17 13:28:46] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-11-17 13:28:48] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-11-17 13:28:48] WARNING - export.py - Failed to import pytorch_quantization
[2023-11-17 13:28:48] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
loading annotations into memory...
Done (t=4.41s)
creating index...
index created!
Creating sub-dataset , this will take a while but don't worry, it only runs once and caches the results
Processed images: 15920/15921, generated 15875 qualified images: 100%|██████████████████████████████████████████████████████████████| 15921/15921 [37:15<00:00,  7.12it/s]
Number of images in sub-dataset:  15875
loading annotations into memory...
Done (t=0.76s)
creating index...
index created!
Creating sub-dataset , this will take a while but don't worry, it only runs once and caches the results
Processed images: 1899/1900, generated 1900 qualified images: 100%|███████████████████████████████████████████████████████████████████| 1900/1900 [02:58<00:00, 10.63it/s]
Number of images in sub-dataset:  1900
[2023-11-17 14:09:08] INFO - checkpoint_utils.py - Successfully loaded pretrained weights for architecture ddrnet_23
[2023-11-17 14:09:08] WARNING - sg_trainer.py - Train dataset size % batch_size != 0 and drop_last=False, this might result in smaller last batch.
[2023-11-17 14:09:09] INFO - sg_trainer.py - Starting a new run with `run_id=RUN_20231117_140909_115891`
[2023-11-17 14:09:09] INFO - sg_trainer.py - Checkpoints directory: ckpts_dir/transfer_learning_semantic_segementation_DDR_NET_23/RUN_20231117_140909_115891
The console stream is now moved to ckpts_dir/transfer_learning_semantic_segementation_DDR_NET_23/RUN_20231117_140909_115891/console_Nov17_14_09_09.txt
[2023-11-17 14:09:10] ERROR - sg_trainer_utils.py - Uncaught exception
Traceback (most recent call last):
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/train.py", line 85, in <module>
    trainer.train(model=model, training_params=train_params, train_loader=train_dataloader, valid_loader=val_dataloader)
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 1419, in train
    first_batch = next(iter(self.train_loader))
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 142, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 142, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/banana/Docs/VScode/Python/RSM_projects/Auto_Pilot/Kromka_Semantic/ddr-net-semantic-hypothesis/ddr_hyp/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 161, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable
```
After loading the dataset, the following error occurs. I tried to add the collate_fn function, but it didn't help
