### ISSUE TITLE
Importing error after fresh installation

### ISSUE THREAD

**Issue by Bueddi** [Deci-AI/super-gradients#1623]
### 🐛 Describe the bug

I recently installed super-gradients on a fresh Python 3.8 virtual environment and get a error after importing the package:

`
import super_gradients

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\super_gradients\__init__.py", line 4, in <module>
    from super_gradients.training import losses, utils, datasets_utils, DataAugmentation, Trainer, KDTrainer, QATTrainer
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\super_gradients\training\__init__.py", line 2, in <module>
    import super_gradients.training.utils.distributed_training_utils as distributed_training_utils
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\super_gradients\training\utils\__init__.py", line 13, in <module>
    from super_gradients.training.utils.early_stopping import EarlyStop
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\super_gradients\training\utils\early_stopping.py", line 1, in <module>
    from super_gradients.training.utils.callbacks import PhaseCallback, Phase, PhaseContext
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\super_gradients\training\utils\callbacks\__init__.py", line 2, in <module>
    from super_gradients.training.utils.callbacks.callbacks import (
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\super_gradients\training\utils\callbacks\callbacks.py", line 29, in <module>
    from super_gradients.common.sg_loggers.time_units import GlobalBatchStepNumber, EpochNumber
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\super_gradients\common\sg_loggers\__init__.py", line 1, in <module>
    from super_gradients.common.sg_loggers.base_sg_logger import BaseSGLogger
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\super_gradients\common\environment\monitoring\__init__.py", line 1, in <module>
    from super_gradients.common.environment.monitoring.monitoring import SystemMonitor
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\super_gradients\common\environment\monitoring\monitoring.py", line 8, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "C:\Users\buettnej\PycharmProjects\DetectorTraining\venv\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'
`

Do you know how to resolve this issue?

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA T1200 Laptop GPU
Nvidia driver version: 529.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:

**Comment by BloodAxe** [comment]
Can you post version of protobuf, tensorboard and tensorflow you get installed?

**Comment by Bueddi** [comment]
Here your are:

protobuf 3.20.3
tensorboard 2.13.0
tensorflow 2.13.0

**Comment by BloodAxe** [comment]
Try `pip uninstall tensorflow` 😅 
Based on your stacktrace, tensorboard package attempts to import TF and something fails (Could be that tensorboard version and tensorflow version are not compatible).
The fact is TB does not require TF to be installed (I have same version of TB and I don't have TF in my env), and can work without tensorflow.
So uninstalling TF could be an options.
If you still need tensorflow, you can try upgrading tensorboard to latest version. This may also help.

**Comment by Bueddi** [comment]
Thanks for your solution, but I actually installed every package (super-gradient, tensorflow - in that order) again and everything works now. Don't know what resolves this, but I can assist your to figure what happining there.
