### ISSUE TITLE
ckpt layer neck.neck1.reduce_skip1.conv.weight with shape torch.Size([192, 384, 1, 1]) does not match backbone.context_module.cv1.conv.weight with shape torch.Size([384, 768, 1, 1]) in the model

### ISSUE THREAD

**Issue by qqqtwh** [Deci-AI/super-gradients#1648]
### 🐛 Describe the bug

from super_gradients.training import models

model = models.get(model_name='yolo_nas_s',num_classes=80,pretrained_weights="coco")

print(model('backone'))
#==============

Traceback (most recent call last):
  File "tools/train.py", line 164, in <module>
    main()
  File "tools/train.py", line 154, in main
    model = models.get(model_name=cfg['model_name'], num_classes=len(cfg['data_classes']), pretrained_weights="coco")
  File "/opt/conda/envs/yolonas330/lib/python3.8/site-packages/super_gradients/training/models/model_factory.py", line 224, in get
    net = instantiate_model(model_name, arch_params, checkpoint_num_classes, pretrained_weights, download_required_code)
  File "/opt/conda/envs/yolonas330/lib/python3.8/site-packages/super_gradients/training/models/model_factory.py", line 166, in instantiate_model
    load_pretrained_weights(net, model_name, pretrained_weights)
  File "/opt/conda/envs/yolonas330/lib/python3.8/site-packages/super_gradients/training/utils/checkpoint_utils.py", line 1576, in load_pretrained_weights
    _load_weights(architecture, model, pretrained_state_dict)
  File "/opt/conda/envs/yolonas330/lib/python3.8/site-packages/super_gradients/training/utils/checkpoint_utils.py", line 1601, in _load_weights
    adaptive_load_state_dict(net=model, state_dict=pretrained_state_dict, strict=StrictLoad.NO_KEY_MATCHING, solver=solver)
  File "/opt/conda/envs/yolonas330/lib/python3.8/site-packages/super_gradients/training/utils/checkpoint_utils.py", line 90, in adaptive_load_state_dict
    adapted_state_dict = adapt_state_dict_to_fit_model_layer_names(net.state_dict(), state_dict, solver=solver)
  File "/opt/conda/envs/yolonas330/lib/python3.8/site-packages/super_gradients/training/utils/checkpoint_utils.py", line 1447, in adapt_state_dict_to_fit_model_layer_names
    new_ckpt_dict = solver(model_state_dict, source_ckpt)
  File "/opt/conda/envs/yolonas330/lib/python3.8/site-packages/super_gradients/training/utils/checkpoint_utils.py", line 201, in __call__
    raise ValueError(f"ckpt layer {ckpt_key} with shape {ckpt_val.shape} does not match {model_key}" f" with shape {model_val.shape} in the model")
ValueError: ckpt layer neck.neck1.reduce_skip1.conv.weight with shape torch.Size([192, 384, 1, 1]) does not match backbone.context_module.cv1.conv.weight with shape torch.Size([384, 768, 1, 1]) in the model

### Versions

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.13.0
[pip3] onnx-simplifier==0.4.35
[pip3] onnxruntime==1.13.1
[pip3] torch==2.1.0
[pip3] torchmetrics==0.8.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.16.0
[pip3] triton==2.1.0
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.16.0                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by shaydeci** [comment]
Thank you @qqqtwh we will look into it.
Can you please share your code?

**Comment by qqqtwh** [comment]
@shaydeci 
After using Torch version==2.0.1, the bug disappeared
