### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by desroberto** [Deci-AI/super-gradients#1703]
### 💡 Your Question

Hey everyone. _I am running into the kind of error that makes me wonder if I should stop coding and apply to McDonald's._ I am unable to run a simple object detection using Yolo Nas or pose estimation using Yolo Nas Pose on a simple Image. 

What I find extremely bizzare is that I have successfully used YoloNas Pose with a video from which this image was obtained, and I have also been able to use it on this same image in the past without errors! As far as I am concerned, my environment has not changed. 

My code, corresponding image, and terminal output are below:

```
import cv2
import sys
import numpy as np
import torch
import os
import pathlib
import re

from super_gradients.training import models
from super_gradients.common.object_names import Models

img_input_file = "../Swings/Back/Pro/Rory/RoryScreenshot.png"

yolo_nas = models.get("yolo_nas_s", pretrained_weights="coco").to("cpu")

yolo_nas.predict(img_input_file, conf=0.25).show()

```

<img width="1285" alt="RoryScreenshot" src="https://github.com/Deci-AI/super-gradients/assets/55507186/fcd8430d-1cb0-4c14-9604-0313135af9cc">

The terminal output is as follows:

(python3.9-env) deisi@MacBook-Air-3 Scripts % python3.9 ImgYOLONAS.py
The console stream is logged into /Users/deisi/sg_logs/console.log
[2023-12-12 19:51:24] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-12-12 19:51:24] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-12-12 19:51:24,356] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[2023-12-12 19:51:25] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-12-12 19:51:25] WARNING - export.py - Failed to import pytorch_quantization
[2023-12-12 19:51:25] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-12-12 19:51:25] WARNING - env_sanity_check.py - Failed to verify operating system: Deci officially supports only Linux kernels. Some features may not work as expected.
[2023-12-12 19:51:26] INFO - checkpoint_utils.py - License Notification: YOLO-NAS-POSE pre-trained weights are subjected to the specific license terms and conditions detailed in 
https://github.com/Deci-AI/super-gradients/blob/master/LICENSE.YOLONAS-POSE.md
By downloading the pre-trained weight files you agree to comply with these terms.
[2023-12-12 19:51:26] INFO - checkpoint_utils.py - Successfully loaded pretrained weights for architecture yolo_nas_pose_l
Traceback (most recent call last):
  File "/Users/deisi/Documents/Condor/Scripts/ImgYOLONAS.py", line 33, in <module>
    prediction = yolo_nas_pose.predict(img, conf=0.75)
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/super_gradients/training/models/pose_estimation_models/yolo_nas_pose/yolo_nas_pose_variants.py", line 168, in predict
    return pipeline(images, batch_size=batch_size)  # type: ignore
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 111, in __call__
    return self.predict_images(inputs, batch_size)
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 127, in predict_images
    return self._combine_image_prediction_to_images(result_generator, n_images=len(images))
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 386, in _combine_image_prediction_to_images
    images_predictions = [next(iter(images_predictions))]
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 165, in _generate_prediction_result
    yield from self._generate_prediction_result_single_batch(batch_images)
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 187, in _generate_prediction_result_single_batch
    preprocessed_image, processing_metadata = self.image_processor.preprocess_image(image=image.copy())
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/super_gradients/training/processing/processing.py", line 99, in preprocess_image
    processed_image, metadata = processing.preprocess_image(image=processed_image)
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/super_gradients/training/processing/processing.py", line 296, in preprocess_image
    processed_image = _pad_image(image=image, padding_coordinates=padding_coordinates, pad_value=self.pad_value)
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/super_gradients/training/transforms/utils.py", line 151, in _pad_image
    return np.pad(image, pad_width=padding_values, mode="constant", constant_values=constant_values)
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/numpy/lib/arraypad.py", line 805, in pad
    values = _as_pairs(values, padded.ndim)
  File "/Users/deisi/anaconda3/envs/python3.9-env/lib/python3.9/site-packages/numpy/lib/arraypad.py", line 491, in _as_pairs
    x = np.array(x)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.

**Any guidance would be much appreciated!**

**Comment by BloodAxe** [comment]
Maybe not all that bad after all and applying to Macas is a bit too harsh move ;)

1) What SG are you using?
2) Can you load a checkpoint you have (checkpoint = torch.load(...)) and print the entire content of `checkpoint["processing_params"]` ?

Something seems to be off with the paddings values in image preprocessing

**Comment by desroberto** [comment]
> Maybe it's not that bad after all and applying to Macas is a bit too harsh move ;)
> 
> 1. What SG are you using?
> 2. Can you load a checkpoint you have (checkpoint = torch.load(...)) and print the entire content of `checkpoint["processing_params"]` ?
> 
> Something seems to be off with the paddings values in image preprocessing

Hey, I appreciate the fast response.

It turns out that it was an issue with the Numpy version. For some reason, when running pip list, and numpy.__version__ the shown version was 1.23. However, for some reason version 1.26 was conflicting. 

after uninstalling Numpy and installing it again, the problem was fixed.

**Comment by BloodAxe** [comment]
So what numpy version was causing issues originally! 1.26?

**Comment by desroberto** [comment]
Yes. Version 1.26 was getting involved for some reason that I don't understand. Bizarre, as when running pip list, and numpy.__version__ the shown version was 1.23. My guess is that it got installed while installing another package that had a numpy dependency, or some other installation issue.
