### ISSUE TITLE
How to install super-gradients in jetson nano? 

### ISSUE THREAD

**Issue by akashpat1098** [Deci-AI/super-gradients#1853]
### 💡 Your Question

Subject: Issue Installing super-gradient Package on Jetson Nano

---

Hi there,

I am currently working on implementing YOLO NAS (Neural Architecture Search) and have successfully trained my model. Now, I am in the process of running the trained model on a Jetson Nano (2GB) for inference.

To perform inference with YOLO NAS on the Jetson Nano, I understand that I need to install the "super-gradient" package, which provides a "get" method for inference.

This is the kind of code I am using,
  ```bash
import super_gradients
yolo_nas = super_gradients.training.models.get("yolo_nas_l", pretrained_weights="coco").cuda()
model_predictions  = yolo_nas.predict("https://deci-pretrained-models.s3.amazonaws.com/sample_images/beatles-abbeyroad.jpg").show()
  ```
 However, I am encountering difficulties during the installation process.

I have followed the installation instructions using the command:

- **Installation Command:**

  ```bash
  pip install super-gradient
  ```
Unfortunately, I am facing the following error:

```
Building wheels for collected packages: onnxsim
  Building wheel for onnxsim (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      running create_version
      creating build
      creating build/lib.linux-aarch64-3.8
      creating build/lib.linux-aarch64-3.8/onnxsim
      copying onnxsim/model_info.py -> build/lib.linux-aarch64-3.8/onnxsim
      copying onnxsim/model_checking.py -> build/lib.linux-aarch64-3.8/onnxsim
      copying onnxsim/__init__.py -> build/lib.linux-aarch64-3.8/onnxsim
      copying onnxsim/version.py -> build/lib.linux-aarch64-3.8/onnxsim
      copying onnxsim/__main__.py -> build/lib.linux-aarch64-3.8/onnxsim
      copying onnxsim/onnx_simplifier.py -> build/lib.linux-aarch64-3.8/onnxsim
      running egg_info
      writing onnxsim.egg-info/PKG-INFO
      writing dependency_links to onnxsim.egg-info/dependency_links.txt
      writing entry points to onnxsim.egg-info/entry_points.txt
      writing requirements to onnxsim.egg-info/requires.txt
      writing top-level names to onnxsim.egg-info/top_level.txt
      reading manifest file 'onnxsim.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c' under directory 'onnxsim'
      warning: no files found matching '*.proto' under directory 'onnxsim'
      warning: no previously-included files matching '*' found under directory 'third_party/onnxruntime'
      warning: no previously-included files matching '*' found under directory 'third_party/onnx-optimizer/build'
      warning: no previously-included files matching '*' found under directory 'third_party/onnx/build'
      warning: no previously-included files matching '*' found under directory 'third_party/onnx/onnx/backend'
      writing manifest file 'onnxsim.egg-info/SOURCES.txt'
      copying onnxsim/cpp2py_export.cc -> build/lib.linux-aarch64-3.8/onnxsim
      copying onnxsim/cxxopts.hpp -> build/lib.linux-aarch64-3.8/onnxsim
      copying onnxsim/onnxsim.cpp -> build/lib.linux-aarch64-3.8/onnxsim
      copying onnxsim/onnxsim.h -> build/lib.linux-aarch64-3.8/onnxsim
      creating build/lib.linux-aarch64-3.8/onnxsim/bin
      copying onnxsim/bin/onnxsim_bin.cpp -> build/lib.linux-aarch64-3.8/onnxsim/bin
      copying onnxsim/bin/onnxsim_option.cpp -> build/lib.linux-aarch64-3.8/onnxsim/bin
      copying onnxsim/bin/onnxsim_option.h -> build/lib.linux-aarch64-3.8/onnxsim/bin
      running build_ext
      running cmake_build
 Run command ['/usr/bin/cmake', '-DPython_INCLUDE_DIR=/usr/include/python3.8', '-DPython_EXECUTABLE=/home/akash/Desktop/AkashCodes/BtechProject/myenv/bin/python', '-DPYTHON_EXECUTABLE=/home/akash/Desktop/AkashCodes/BtechProject/myenv/bin/python', '-DBUILD_ONNX_PYTHON=OFF', '-DONNXSIM_PYTHON=ON', '-DONNXSIM_BUILTIN_ORT=OFF', '-DONNX_USE_LITE_PROTO=OFF', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-38-aarch64-linux-gnu.so', '-DONNX_OPT_USE_SYSTEM_PROTOBUF=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-8jv7ddgd/onnxsim_0c5854ac48fd4f5ba3360977a0269ac0']
      CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
        CMake 3.22 or higher is required.  You are running version 3.10.2
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8jv7ddgd/onnxsim_0c5854ac48fd4f5ba3360977a0269ac0/setup.py", line 279, in <module>
          setuptools.setup(
        File "/home/akash/Desktop/AkashCodes/BtechProject/myenv/lib/python3.8/site-packages/setuptools/__init__.py", line 129, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
          self.run_command('build')
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-8jv7ddgd/onnxsim_0c5854ac48fd4f5ba3360977a0269ac0/setup.py", line 220, in run
          self.run_command('cmake_build')
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-8jv7ddgd/onnxsim_0c5854ac48fd4f5ba3360977a0269ac0/setup.py", line 194, in run
          subprocess.check_call(cmake_args)
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPython_INCLUDE_DIR=/usr/include/python3.8', '-DPython_EXECUTABLE=/home/akash/Desktop/AkashCodes/BtechProject/myenv/bin/python', '-DPYTHON_EXECUTABLE=/home/akash/Desktop/AkashCodes/BtechProject/myenv/bin/python', '-DBUILD_ONNX_PYTHON=OFF', '-DONNXSIM_PYTHON=ON', '-DONNXSIM_BUILTIN_ORT=OFF', '-DONNX_USE_LITE_PROTO=OFF', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-38-aarch64-linux-gnu.so', '-DONNX_OPT_USE_SYSTEM_PROTOBUF=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-8jv7ddgd/onnxsim_0c5854ac48fd4f5ba3360977a0269ac0']' returned non-zero exit status 1.
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnxsim
  Running setup.py clean for onnxsim
Failed to build onnxsim
ERROR: Could not build wheels for onnxsim, which is required to install pyproject.toml-based projects
```
By looking at the error , it seems like there is error in building onnxsim wheel. 

Please help me , I do not know how do I proceed further due to which I am unable to run the YOLO NAS model in jetson nano. 
Given the current roadblock, I am open to exploring alternative methods for running the YOLO NAS model on the Jetson Nano. If there are any recommended alternatives or workarounds, please provide the necessary guidance.

I would appreciate any guidance or assistance you can provide to resolve this issue and successfully install the super-gradient package on my Jetson Nano.

Thank you for your time and support.

**Comment by BloodAxe** [comment]
To run model on Jetson (especially a Nano) you should NOT use native pytorch model - it would be horribly slow.
Instead you should consider running a model using TensorRT. For this you need to export YoloNAS to ONNX graph first and then convert it to TRT engine.

You can learn how to do it here:
* https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/examples/model_export/models_export.ipynb
* https://github.com/Deci-AI/super-gradients/blob/master/notebooks/YoloNAS_Inference_using_TensorRT.ipynb
