### ISSUE TITLE
super-gradients is not getting installed. "build wheel ... error. error: subprocess-exited-with-error"

### ISSUE THREAD

**Issue by Itachi-6** [Deci-AI/super-gradients#1854]
### 💡 Your Question

I'm using Ubuntu 23.10. While I'm installing super-gradients using pip, it stops at some point and says there is an error while building the wheel. My python version is 3.12.0. Please help. Please feel free to ask if any other information is needed.

### Versions

  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/dilipraj6/Dev/Environments/Pushup Counter/pushup/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/dilipraj6/Dev/Environments/Pushup Counter/pushup/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/dilipraj6/Dev/Environments/Pushup Counter/pushup/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0wbzuv9z/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0wbzuv9z/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-0wbzuv9z/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 61, in <module>
      AssertionError: Could not find cmake in PATH
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by BloodAxe** [comment]
`Could not find cmake in PATH` is your issue. You have to new python interpreter and not all packages has pre-built wheels in PyPy. Install build essentials for your platform to be able to compile C++ code.
This is not issue of super-gradients. Simply during installations of some dependencies (Most likely onnx) pip tries to compile this package from source and fails that you don't have CMake and C++ compiler.
