### ISSUE TITLE
pip install super-gradients failed

### ISSUE THREAD

**Issue by randubin** [Deci-AI/super-gradients#1892]
### 🐛 Describe the bug

When trying to install throw pip:
Requirement already satisfied: PyYAML>=5.1.0 in c:\users\randubin\anaconda3\lib\site-packages (from omegaconf->super-gradients) (6.0)
INFO: pip is looking at multiple versions of onnx to determine which version is compatible with other requirements. This could take a while.
Collecting onnx>=1.10.1 (from super-gradients)
  Obtaining dependency information for onnx>=1.10.1 from https://files.pythonhosted.org/packages/db/2d/0851d7bb5ae1d08cc27a0ccfba9e77e2393f47ea56e57d347e2926b6d316/onnx-1.15.0-cp311-cp311-win_amd64.whl.metadata
  Using cached onnx-1.15.0-cp311-cp311-win_amd64.whl.metadata (15 kB)
  Obtaining dependency information for onnx>=1.10.1 from https://files.pythonhosted.org/packages/03/49/7263b3806ffebd3c967341986df32a5e62b2fa78beca2cdf9516d876b3fc/onnx-1.14.1-cp311-cp311-win_amd64.whl.metadata
  Using cached onnx-1.14.1-cp311-cp311-win_amd64.whl.metadata (15 kB)
  Obtaining dependency information for onnx>=1.10.1 from https://files.pythonhosted.org/packages/a6/95/ce80f1180b27d6ef0cf65ea82abfea09d0c320f7cbecc36e0a78f20d7888/onnx-1.14.0-cp311-cp311-win_amd64.whl.metadata
  Using cached onnx-1.14.0-cp311-cp311-win_amd64.whl.metadata (15 kB)
  Obtaining dependency information for onnx>=1.10.1 from https://files.pythonhosted.org/packages/72/c6/87d48374e307e16fa6c4ee7c4acde6f3fb83a2ed2d02a8ee1310f85f6e03/onnx-1.13.0-cp311-cp311-win_amd64.whl.metadata
  Using cached onnx-1.13.0-cp311-cp311-win_amd64.whl.metadata (14 kB)
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\RanDubin\AppData\Local\Temp\pip-install-fang1dnr\onnx_98e05720ce3349e0baf25a5464dbbe4e\setup.py", line 81, in <module>
          assert CMAKE, "Could not find cmake executable!"
      AssertionError: Could not find cmake executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Versions

>pip install super-gradients

**Comment by BloodAxe** [comment]
It seems there are no prebuild wheels for one of the dependencies (onnx) for your platform (win) & python version (3.11). So pip tries to compile this package, but it fails because your system does not have a compiler installed. 
You would need to install a [Visual Studio Build Tools](https://visualstudio.microsoft.com/downloads/?q=build+tools) in order to be able to compile C++ code for some packages. Or you can going for python 3.8 / 3.9 which is more likely to have prebuilt wheels for onnx.

**Comment by randubin** [comment]
Thanks. I tried to solve it with py 3.11 without success including the visual sutdio tools and other recommended steps  in the web.
virtual enviroment with py3.9 works. 
Thanks

**Comment by MRo47** [comment]
Been trying to run this on colab. Fails as colab default python is now 3.11

This helped me get a python 3.10 in colab: [kaggle article](https://www.kaggle.com/code/alaajah/creating-virtual-environment-on-google-colab)
