### ISSUE TITLE
onnx export error: MemoryError: std::bad_alloc in onnxsim

### ISSUE THREAD

**Issue by mayorblock** [Deci-AI/super-gradients#1957]
### 🐛 Describe the bug

First, thank you for a great model suite and package setup. It is very much appreciated :)

After upgrading to SG version `3.7.1` I get a memory error in the onnx export during `onnx.simplify`.  A minimal reproducible example is your [export notebook](https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/examples/model_export/models_export.ipynb):

```python
from super_gradients.common.object_names import Models
from super_gradients.training import models

model = models.get(Models.YOLO_NAS_S, pretrained_weights="coco")

export_result = model.export("yolo_nas_s.onnx")
```
Running this gives
```
...
[2024-04-11 10:38:13] INFO - checkpoint_utils.py - Successfully loaded pretrained weights for architecture yolo_nas_s
...envs/yolonas_v36/lib/python3.10/site-packages/torch/onnx/symbolic_opset9.py:5859: UserWarning: Exporting aten::index operator of advanced indexing in opset 17 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn(
Traceback (most recent call last):
  File ".../scripts/onnx_export_memory_error.py", line 6, in <module>
    export_result = model.export("yolo_nas_s.onnx")
  File ".../envs/yolonas_v36/lib/python3.10/site-packages/super_gradients/module_interfaces/exportable_detector.py", line 515, in export
    model_opt, simplify_successful = onnxsim.simplify(output)
  File "envs/yolonas_v36/lib/python3.10/site-packages/onnxsim/onnx_simplifier.py", line 197, in simplify
    model_opt_bytes = C.simplify(
MemoryError: std::bad_alloc
```
I have tried different OPSET version (` onnx_export_kwargs= {"opset_version": 14}`) and downgrading `onnxsim` but the issue persists.

However, it works either by setting `onnx_simplify=False` or reverting all onnx packages to my "old" versions (worked with SG `3.2.1`)
```
onnx                      1.13.0                   pypi_0    pypi
onnx-graphsurgeon         0.3.27                   pypi_0    pypi
onnx-simplifier           0.4.33                   pypi_0    pypi
onnxruntime               1.13.1                   pypi_0    pypi
```
Unfortunately this is at odds with `requirements.txt` to have `onnx==1.15.0 `. Also, I see there has been quite some changes to `super_gradients.module_interfaces.ExportableObjectDetectionModel` so I am a little unsure what to actual problem is...

### Versions

Collecting environment information...
PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (x86_64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.14 (main, Mar 21 2024, 11:24:58) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.15.0
[pip3] onnx-graphsurgeon==0.3.27
[pip3] onnxruntime==1.15.0
[pip3] onnxsim==0.4.36
[pip3] torch==2.2.2
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.17.2

**Comment by BloodAxe** [comment]
You can try downgrading onnxsim to 4.35 or earlier to see if the problem exists.
An error you are getting indicates some crash in C++ internals in `onnxsim`. It is impossible for me to say what is going wrong here. Is it a new environment? What was the previous onnxsim version that worked for you?

**Comment by mayorblock** [comment]
Hi @BloodAxe, thanks for getting back.

Same error for onnxsim 4.35 and 4.34. And yes, this is a new environment. What worked was:
<img width="850" alt="image" src="https://github.com/Deci-AI/super-gradients/assets/126508264/80475476-aa66-47cd-b430-71884d53eb9d">

Let me know if there is any additional information I could extract to identify the underlying issue.
