### ISSUE TITLE
Failed to import pytorch_quantization

### ISSUE THREAD

**Issue by mriamnobody** [Deci-AI/super-gradients#996]
I have used to following code for testing (available in documentation):

```
import super_gradients

yolo_nas = super_gradients.training.models.get("yolo_nas_l", pretrained_weights="coco").cuda()
yolo_nas.predict("https://deci-pretrained-models.s3.amazonaws.com/sample_images/beatles-abbeyroad.jpg").show()
```
but I received the following error:

```
The console stream is logged into /home/ethan/sg_logs/console.log
[2023-05-14 13:39:15] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-05-14 13:39:32] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-05-14 13:39:32] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-05-14 13:39:32] WARNING - export.py - Failed to import pytorch_quantization
[2023-05-14 13:39:32] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-05-14 13:39:33] INFO - checkpoint_utils.py - License Notification: YOLO-NAS pre-trained weights are subjected to the specific license terms and conditions detailed in
https://github.com/Deci-AI/super-gradients/blob/master/LICENSE.YOLONAS.md
By downloading the pre-trained weight files you agree to comply with these terms.
Could not load library libcudnn_cnn_infer.so.8. Error: libcuda.so: cannot open shared object file: No such file or directory
Aborted
```

### Environment:
 - OS
```
Linux 5.10.16.3-microsoft-standard-WSL2 x86_64
```
 - Nvidia 3090
 - Super Gradients version: 3.1.1
 - Python environment: 3.10.6
```
absl-py==1.4.0
alabaster==0.7.13
antlr4-python3-runtime==4.9.3
attrs==23.1.0
Babel==2.12.1
boto3==1.26.133
botocore==1.29.133
build==0.10.0
cachetools==5.3.0
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
coloredlogs==15.0.1
contourpy==1.0.7
coverage==5.3.1
cycler==0.11.0
Deprecated==1.2.13
docutils==0.17.1
einops==0.3.2
flatbuffers==23.5.9
fonttools==4.39.4
future==0.18.3
google-auth==2.18.0
google-auth-oauthlib==1.0.0
grpcio==1.54.2
humanfriendly==10.0
hydra-core==1.3.2
idna==3.4
imagesize==1.4.1
Jinja2==3.1.2
jmespath==1.0.1
json-tricks==3.16.1
jsonschema==4.17.3
kiwisolver==1.4.4
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
matplotlib==3.7.1
mdurl==0.1.2
mpmath==1.3.0
numpy==1.23.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.2
omegaconf==2.3.0
onnx==1.13.0
onnx-simplifier==0.4.28
onnxruntime==1.13.1
opencv-python==4.7.0.72
packaging==23.1
Pillow==9.5.0
pip-tools==6.13.0
protobuf==3.20.3
psutil==5.9.5
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycocotools==2.0.4
pyDeprecate==0.3.2
Pygments==2.15.1
pyparsing==2.4.5
pyproject_hooks==1.0.0
pyrsistent==0.19.3
python-dateutil==2.8.2
PyYAML==6.0
rapidfuzz==3.0.0
requests==2.30.0
requests-oauthlib==1.3.1
rich==13.3.5
rsa==4.9
s3transfer==0.6.1
scipy==1.10.1
six==1.16.0
snowballstemmer==2.2.0
Sphinx==4.0.3
sphinx-rtd-theme==1.2.0
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stringcase==1.2.0
super-gradients==3.1.1
sympy==1.12
tensorboard==2.13.0
tensorboard-data-server==0.7.0
termcolor==1.1.0
tomli==2.0.1
torch==1.13.1+cu117
torchaudio==0.13.1+cu117
torchmetrics==0.8.0
torchvision==0.14.1+cu117
tqdm==4.65.0
treelib==1.6.1
typing_extensions==4.5.0
urllib3==1.26.15
Werkzeug==2.3.4
wrapt==1.15.0
```

**Comment by Louis-Dupont** [comment]
Hi @mriamnobody 
It seems to be related to `cudnn` and not `SuperGradients`. 
You can check out the following resources, it might help you;
- https://stackoverflow.com/questions/66977227/could-not-load-dynamic-library-libcudnn-so-8-when-running-tensorflow-on-ubun
- https://discuss.pytorch.org/t/libcudnn-cnn-infer-so-8-library-can-not-found/164661

**Comment by mriamnobody** [comment]
Thank you @Louis-Dupont for providing the links/source to resolve an issue which is not related to super-gradients. I tried to perform the steps mentioned in the StackOverflow link and it got rid of the error ```Could not load library libcudnn_cnn_infer.so.8. Error: libcuda.so: cannot open shared object file: No such file or directory
Aborted``` the following errors were still present:
```
[2023-05-15 06:43:25] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-05-15 06:43:25] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-05-15 06:43:25] WARNING - export.py - Failed to import pytorch_quantization
[2023-05-15 06:43:25] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
```

So did some searching on internet and found that two more modules need to be installed:
`nvidia-pyindex` and `pytorch-quantization`. For anyone in future gets this issue, you first need to install the `nvidia-pyindex` and then `pytorch-quantization` else if you try to install `pytorch-quantization` first and then `nvidia-pyindex` you will the following error:

```
Collecting pytorch-quantization
  Downloading pytorch-quantization-0.0.1.dev5.tar.gz (7.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-t9i6zekc/pytorch-quantization_9cb4035ffda345a7959b12c1917f5e0c/setup.py", line 150, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install pytorch-quantization
      ```
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mriamnobody** [comment]
@Louis-Dupont 
I have still one query related to this problem after performing the steps unnecessary to resolve the issue I'm facing what shall be the output of this code:

```
import super_gradients

yolo_nas = super_gradients.training.models.get("yolo_nas_l", pretrained_weights="coco").cuda()
yolo_nas.predict("https://deci-pretrained-models.s3.amazonaws.com/sample_images/beatles-abbeyroad.jpg").show()

```

When the above code is run I only get the following on terminal:

```
The console stream is logged into /home/ethan/sg_logs/console.log
[2023-05-15 06:49:10] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
```

and it takes close to 25 seconds for the script to complete. Also, the load on GPU fluctuates from 10% to 100% while the script is running. Am I missing something?

**Comment by Louis-Dupont** [comment]
Is this all the logs you had in the terminal? Because if its the first time you run, it makes sense it would take more time because it downloads the model, but you should have logs like:
<img width="1008" alt="image" src="https://github.com/Deci-AI/super-gradients/assets/35190946/4021ff3a-8a71-4c98-bfaf-c3ba31417f69">

Try rerunning it again after the model is downloaded it should be way faster.

**Comment by mriamnobody** [comment]
Thanks for your reply @Louis-Dupont. Nothing is being displayed on my terminal except the text which I shared in my last comment. No model download progress bar nothing. I have attached a screenshot for your reference.

**Comment by Louis-Dupont** [comment]
Let's see what takes time.

``` python
import time
import torch

start_predict = time.perf_counter()


from super_gradients.common.object_names import Models
from super_gradients.training import models

post_import_time = time.perf_counter()
print("Loading SG: ", post_import_time - start_predict)

# Note that currently only YoloX, PPYoloE and YOLO-NAS are supported.
model = models.get(Models.YOLO_NAS_L, pretrained_weights="coco")

# We want to use cuda if available to speed up inference.
model = model.to("cuda" if torch.cuda.is_available() else "cpu")


post_model_time = time.perf_counter()
print("Loading Model: ", post_model_time - post_import_time)


images_predictions = model.predict(
    "../../../../documentation/source/images/examples/pose_elephant_flip.gif",
)

post_predict_time = time.perf_counter()
print("Predict: ", post_predict_time - post_model_time)

```

**Comment by mriamnobody** [comment]
Below are the results of three consecutive runs. The first run took a bit longer than the succeeding two. The script took close to below 45 seconds to complete its execution. I have attached the console image for your reference.

![Screenshot (2333)](https://github.com/Deci-AI/super-gradients/assets/14347205/fd386f1f-82cb-4bf2-b4e7-53b411edfd44)
